import LeanCfgProject.TCS1.LinearRegularIntersection
import LeanCfgProject.TCS1.FixedHSubstitutability
import LeanCfgProject.TCS1.FixedHomEvaluation
import LeanCfgProject.TCS1.FixedHTypingRefinement
import LeanCfgProject.TCS1.GoldCompatibilityFiniteObstruction
import LeanCfgProject.TCS1.SyntacticRefinementRegularity
import LeanCfgProject.TCS1.RegularRecognition
import LeanCfgProject.TCS1.ClarkEyraudSpecialCase
import LeanCfgProject.TCS1.FixedHFiniteObstructions
import LeanCfgProject.TCS1.FiniteMonoidObstructionKernel
import LeanCfgProject.TCS1.UncappedCounterObstruction
import LeanCfgProject.TCS1.CappedCounterFixedWindow
import LeanCfgProject.TCS1.CappedCounterFiniteState
import LeanCfgProject.TCS1.CappedCounterPaperWitness
import LeanCfgProject.TCS1.CappedCounterProposition
import LeanCfgProject.TCS1.DeltaStarFixedWindow
import LeanCfgProject.TCS1.DeltaStarTyping
import LeanCfgProject.TCS1.DeltaStarFixedH
import LeanCfgProject.TCS1.DeltaStarFixedHSubstitutability
import LeanCfgProject.TCS1.DeltaStarNonregular
import LeanCfgProject.TCS1.DeltaStarDisplayedGrammar
import LeanCfgProject.TCS1.DeltaStarBinaryGrammar
import LeanCfgProject.TCS1.DeltaStarNonlinearityBridge
import LeanCfgProject.TCS1.DeltaStarDoubleDeltaNonlinear
import LeanCfgProject.TCS1.DeltaStarFourBlockDFA
import LeanCfgProject.TCS1.DeltaStarNonlinearityReduction
import LeanCfgProject.TCS1.DeltaStarProposition
import LeanCfgProject.TCS1.DyckOneBracketKernel
import LeanCfgProject.TCS1.DyckOneBracketGrammar
import LeanCfgProject.TCS1.LukasiewiczBoundary
import LeanCfgProject.TCS1.LukasiewiczGrammar
import LeanCfgProject.TCS1.FixedHRightQuotient
import LeanCfgProject.TCS1.LinearSeparatorExample
import LeanCfgProject.TCS1.LinearSeparatorTyping
import LeanCfgProject.TCS1.LinearSeparatorDistribution
import LeanCfgProject.TCS1.LinearSeparatorPowerContexts
import LeanCfgProject.TCS1.LinearSeparatorFactorSlices
import LeanCfgProject.TCS1.LinearSeparatorContextShape
import LeanCfgProject.TCS1.LinearSeparatorBoundaryFactors
import LeanCfgProject.TCS1.LinearSeparatorBalance
import LeanCfgProject.TCS1.LinearSeparatorFixedH
import LeanCfgProject.TCS1.LinearSeparatorProposition86
import LeanCfgProject.TCS1.LinearSeparatorDisplayedGrammar
import LeanCfgProject.TCS1.LinearSeparatorNonregular
import LeanCfgProject.TCS1.LinearSeparatorPreparedGrammar
import LeanCfgProject.TCS1.ClarkCongruentialKernel
import LeanCfgProject.TCS1.YieldTypedRefinementCore
import LeanCfgProject.TCS1.ReconstructionSoundness
import LeanCfgProject.TCS1.ReconstructionCFGPresentation
import LeanCfgProject.TCS1.ReconstructionFiniteStateSupport
import LeanCfgProject.TCS1.ReconstructionActiveGrammar
import LeanCfgProject.TCS1.ReconstructionUnitFreeBridge
import LeanCfgProject.TCS1.ReconstructionCYKBridge
import LeanCfgProject.TCS1.FiniteUnitReachability
import LeanCfgProject.TCS1.ReconstructionFactorSlotState
import LeanCfgProject.TCS1.ReconstructionFactorSlotGrammar
import LeanCfgProject.TCS1.ReconstructionFactorSlotCYK
import LeanCfgProject.TCS1.ReconstructionProductionTables
import LeanCfgProject.TCS1.ExecutableConservativeLearner
import LeanCfgProject.TCS1.MaterializedConservativeLearner
import LeanCfgProject.TCS1.MaterializedProductionCost
import LeanCfgProject.TCS1.SingletonDataLowerBound
import LeanCfgProject.TCS1.DoublingSingletonGrammar
import LeanCfgProject.TCS1.ExecutableSmokeTest
import LeanCfgProject.TCS1.ReconstructionComplexityCounts
import LeanCfgProject.TCS1.ReconstructionFiniteCandidateSpaces
import LeanCfgProject.TCS1.BatchLanguageMonotonicity
import LeanCfgProject.TCS1.CanonicalWitnessCompleteness
import LeanCfgProject.TCS1.ConservativeGoldKernel
import LeanCfgProject.TCS1.WitnessSetConstruction
import LeanCfgProject.TCS1.CanonicalWitnessCounting
import LeanCfgProject.TCS1.ReducednessWitnessChoices
import LeanCfgProject.TCS1.MinimalReducedWitnessChoices
import LeanCfgProject.TCS1.GoldConvergenceClosure
import LeanCfgProject.TCS1.GoldCharacteristicBridge
import LeanCfgProject.TCS1.ConcreteConservativeLearner
import LeanCfgProject.TCS1.ConcreteLearnerComplexity
import LeanCfgProject.TCS1.BinaryMembershipKernel
import LeanCfgProject.TCS1.BinaryMembershipRounds
import LeanCfgProject.TCS1.BinaryMembershipChart
import LeanCfgProject.TCS1.BinaryMembershipSeed
import LeanCfgProject.TCS1.BinaryMembershipChartSound
import LeanCfgProject.TCS1.BinaryMembershipChartComplete
import LeanCfgProject.TCS1.BinaryMembershipChartExact
import LeanCfgProject.TCS1.BinaryMembershipDecision
import LeanCfgProject.TCS1.ConservativeMembershipCost
import LeanCfgProject.TCS1.TrivialTargetEndpoints
import LeanCfgProject.TCS1.IndexedGoldBridge
import LeanCfgProject.TCS1.IndexedConcreteGoldLearner
import LeanCfgProject.TCS1.IndexedFixedHBridge
import LeanCfgProject.TCS1.MainTheoremSemanticPackage
import LeanCfgProject.TCS1.MainTheoremExecutablePackage
import LeanCfgProject.TCS1.MainTheoremMaterializedPackage

import LeanCfgProject.TCS1.SSBNFThicknessBounds
import LeanCfgProject.TCS1.SSBNFNormalizationCombinatorics
import LeanCfgProject.TCS1.FrontEndSizeCombinatorics
import LeanCfgProject.TCS1.FixedWindowCharacteristicDataBounds
import LeanCfgProject.TCS1.FixedWindowCharacteristicDataFacade
import LeanCfgProject.TCS1.FixedWindowTreeCombinatorics
import LeanCfgProject.TCS1.FixedWindowSummarySemantic
import LeanCfgProject.TCS1.FixedWindowConcreteSummary
import LeanCfgProject.TCS1.FixedWindowConcreteMonoid
import LeanCfgProject.TCS1.FixedWindowClassicalSubstitutability
import LeanCfgProject.TCS1.FixedWindowExactEquivalence
import LeanCfgProject.TCS1.FixedWindowCounterexampleCriterion
import LeanCfgProject.TCS1.ZeroWindowEndpoint
import LeanCfgProject.TCS1.FixedWindowConcreteCharacteristicData
import LeanCfgProject.TCS1.FixedWindowSection7Package
import LeanCfgProject.TCS1.FixedWindowBoundarySemantic
import LeanCfgProject.TCS1.MarkedBoundaryKernel
import LeanCfgProject.TCS1.MarkedBoundaryNormalization
import LeanCfgProject.TCS1.MarkedBoundaryGapSemantic
import LeanCfgProject.TCS1.MarkedBoundaryGapNormalization
import LeanCfgProject.TCS1.MarkedBoundaryExpansion
import LeanCfgProject.TCS1.MarkedBoundarySelection
import LeanCfgProject.TCS1.FixedWindowBoundaryMarking
import LeanCfgProject.TCS1.FixedWindowTreeSurgeryFacade
import LeanCfgProject.TCS1.FixedWindowLemma71ReducedFacade
import LeanCfgProject.TCS1.SuccessfulTypedTrimClosureBridge
import LeanCfgProject.TCS1.FixedWindowLemma72Facade
import LeanCfgProject.TCS1.FixedWindowReducedContextFacade
import LeanCfgProject.TCS1.ActiveTypedReachabilityBridge
import LeanCfgProject.TCS1.ConcreteTypedTrimming
import LeanCfgProject.TCS1.ConcreteTypedTrimLanguage
import LeanCfgProject.TCS1.ReducedTypedRuleBridge
import LeanCfgProject.TCS1.ShortestNonemptyPathBound
import LeanCfgProject.TCS1.LinearSpineBounds
import LeanCfgProject.TCS1.LinearSpineSemantic
import LeanCfgProject.TCS1.LinearPumpingKernel
import LeanCfgProject.TCS1.LinearPumpingBounded
import LeanCfgProject.TCS1.RawLinearPumping
import LeanCfgProject.TCS1.LinearTypedShapeBridge
import LeanCfgProject.TCS1.LinearNormalizationSize
import LeanCfgProject.TCS1.LinearNormalizationPlan
import LeanCfgProject.TCS1.PreparedLinearGrammarSemantics
import LeanCfgProject.TCS1.LinearNormalizationRules
import LeanCfgProject.TCS1.LinearNormalizationSoundness
import LeanCfgProject.TCS1.LinearNormalizationCompleteness
import LeanCfgProject.TCS1.PreparedLinearNormalizationFacade
import LeanCfgProject.TCS1.LinearMixedRhsDecomposition
import LeanCfgProject.TCS1.LinearIndexedPreprocessedBridge
import LeanCfgProject.TCS1.LinearConstructedStartLanguage
import LeanCfgProject.TCS1.IndexedPreprocessedLinearCharacteristicData
import LeanCfgProject.TCS1.LinearCharacteristicSourceBounds
import LeanCfgProject.TCS1.IndexedLinearCharacteristicData
import LeanCfgProject.TCS1.LinearRawPreprocessing
import LeanCfgProject.TCS1.LinearRawEpsilonUnitSemantics
import LeanCfgProject.TCS1.LinearRawPreprocessingFacade
import LeanCfgProject.TCS1.LinearRawUnitFreePreparedBridge
import LeanCfgProject.TCS1.IndexedLinearNormalizationFacade
import LeanCfgProject.TCS1.IndexedLinearNormalizationSize
import LeanCfgProject.TCS1.IndexedLinearNormalizationTheorem
import LeanCfgProject.TCS1.IndexedLinearReducedNormalization
import LeanCfgProject.TCS1.LinearRawFinitePreprocessing
import LeanCfgProject.TCS1.LinearReducedWitnessBridge
import LeanCfgProject.TCS1.LinearCharacteristicDataFacade
import LeanCfgProject.TCS1.ConcreteLinearCharacteristicData
import LeanCfgProject.TCS1.LinearCanonicalWitnessBounds
import LeanCfgProject.TCS1.ShortestNonemptySpineSemantic
import LeanCfgProject.TCS1.FiniteSupportSpineBound
import LeanCfgProject.TCS1.BinaryGrammarFiniteRestriction
import LeanCfgProject.TCS1.FixedWindowContextPathBound
import LeanCfgProject.TCS1.FixedWindowContextSemantic

import LeanCfgProject.TCS1.TerminalIsolationKernel
import LeanCfgProject.TCS1.LeastClosedCFGLanguage
import LeanCfgProject.TCS1.GeneralCFGDerivation
import LeanCfgProject.TCS1.BinarizationKernel
import LeanCfgProject.TCS1.BinarizationLeastClosed
import LeanCfgProject.TCS1.SequenceBinaryGrammarBridge
import LeanCfgProject.TCS1.TerminalIsolationBinarizationBridge
import LeanCfgProject.TCS1.FrontEndThicknessKernel
import LeanCfgProject.TCS1.FrontEndBinaryThickness
import LeanCfgProject.TCS1.FrontEndFiniteSupportFacade
import LeanCfgProject.TCS1.FiniteCFGEncoding
import LeanCfgProject.TCS1.IndexedClosedFrontSupport
import LeanCfgProject.TCS1.IndexedFrontRuleClosure
import LeanCfgProject.TCS1.IndexedNormalizationFacade
import LeanCfgProject.TCS1.EpsilonFreeProductiveTrim
import LeanCfgProject.TCS1.IndexedConcreteSSBNFNormalization
import LeanCfgProject.TCS1.IndexedNormalizationLanguage
import LeanCfgProject.TCS1.IndexedNormalizationCounts
import LeanCfgProject.TCS1.IndexedSection7Bridge
import LeanCfgProject.TCS1.NormalizationLanguageBounds
import LeanCfgProject.TCS1.BinaryEpsilonElimination
import LeanCfgProject.TCS1.BinaryUnitElimination
import LeanCfgProject.TCS1.SSBNFNormalizationSemanticKernel
import LeanCfgProject.TCS1.UnitFreeProductiveTrim
import LeanCfgProject.TCS1.UnitFreeReachableTrim
import LeanCfgProject.TCS1.SeparatedStartSSBNF
import LeanCfgProject.TCS1.FixedWindowTransferKernel
import LeanCfgProject.TCS1.Proposition74Facade
import LeanCfgProject.TCS1.Proposition74IndexedPackage

import LeanCfgProject.TCS1.ClarkCongruentialPackaging
import LeanCfgProject.TCS1.ClarkCongruentialIndexedFacade
import LeanCfgProject.TCS1.ClarkCongruentialEndpoints
import LeanCfgProject.TCS1.ClarkCongruentialComparison
import LeanCfgProject.TCS1.V79TheoremSurfaceAudit
import LeanCfgProject.TCS1.V79PreliminariesAudit
import LeanCfgProject.TCS1.V79ManuscriptClaimAudit
import LeanCfgProject.TCS1.V79FrontBackAppendixAudit
import LeanCfgProject.TCS1.V79FullManuscriptAudit
/-!
# TCS #1 v79 Lean verification facade

This module imports every theorem-facing kernel maintained for the current
TCS #1 v79 working baseline.  The v79 manuscript is a non-mathematical
micro-revision of v78, so the theorem surface is inherited unchanged while
this facade tracks the current submission-candidate source. Building this one target is the fast integration
check; CI separately rejects placeholder proofs and project-level axiom declarations
inside the TCS1 namespace.
-/

namespace LeanCfgProject
namespace TCS1

/-- Compatibility marker for the integrated v66 verification facade. -/
theorem v66_facade_loaded : True :=
  True.intro

/-- Marker theorem for the integrated v68 verification facade. -/
theorem v68_facade_loaded : True :=
  True.intro

/-- Compatibility marker for the integrated v77 verification facade. -/
theorem v77_facade_loaded : True :=
  True.intro

/-- Marker theorem for the integrated v78 verification facade. -/
theorem v78_facade_loaded : True :=
  True.intro

/-- Marker theorem for the current v79 verification facade. -/
theorem v79_facade_loaded : True :=
  True.intro

end TCS1
end LeanCfgProject
