import LeanCfgProject.TCS1.BinaryMembershipSeed
import Mathlib.Data.List.TakeDrop

/-!
# TCS #1 v79: soundness of the executable CYK chart

This module connects the finite chart implementation to the grammar semantics.
A chart entry (A,i,j) denotes a derivation of the contiguous input slice
w[i:j].

The terminal seed is sound, and one executable binary-candidate scan preserves
soundness.  Hence every finite chart iteration from the terminal seed contains
only genuine grammar derivations.
-/

namespace LeanCfgProject
namespace TCS1

universe u v

section BinaryMembershipChartSound

variable {N : Type u}
variable {α : Type v}

/-- Contiguous input slice between two CYK boundaries. -/
def cykSlice
    (w : Word α)
    (i j : Fin (w.length + 1)) :
    Word α :=
  (w.drop i.1).take (j.1 - i.1)

/-- Splitting a valid interval at an intermediate boundary splits its slice. -/
theorem cykSlice_split
    (w : Word α)
    (i k j : Fin (w.length + 1))
    (hik : i.1 ≤ k.1)
    (hkj : k.1 ≤ j.1) :
    cykSlice w i j =
      cykSlice w i k ++
        cykSlice w k j := by
  unfold cykSlice
  have hsum :
      j.1 - i.1 =
        (k.1 - i.1) + (j.1 - k.1) := by
    omega
  rw [hsum, List.take_add]
  have hdrop :
      (w.drop i.1).drop (k.1 - i.1) =
        w.drop k.1 := by
    rw [List.drop_drop]
    congr
    omega
  rw [hdrop]

/-- The unit span generated by a terminal candidate is exactly that symbol. -/
theorem cykSlice_terminal
    (w : Word α)
    (i : Fin w.length) :
    cykSlice w
        (cykLeftBoundary i)
        (cykRightBoundary i)
      =
    [w.get i] := by
  unfold cykSlice
  simp only [cykLeftBoundary_val,
    cykRightBoundary_val]
  have hsub :
      i.1 + 1 - i.1 = 1 := by
    omega
  rw [hsub]
  exact
    List.take_one_drop_eq_of_lt_length i.2

/-- Semantic soundness invariant for a finite chart. -/
def CYKChartSound
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (w : Word α)
    (chart : CYKChart N w.length) : Prop :=
  ∀ e,
    e ∈ chart →
    UntypedDerives terminalRule binaryRule
      e.1 (cykSlice w e.2.1 e.2.2)

/-- The executable terminal seed contains only genuine one-letter derivations. -/
theorem cykTerminalSeed_sound
    [Fintype N]
    [DecidableEq N]
    (terminalRule : N → α → Prop)
    [DecidableRel terminalRule]
    (binaryRule : N → N → N → Prop)
    (w : Word α) :
    CYKChartSound terminalRule binaryRule w
      (cykTerminalSeed terminalRule w) := by
  intro e he
  unfold cykTerminalSeed at he
  rcases Finset.mem_image.mp he with
    ⟨c, hc, rfl⟩
  have hen :
      CYKTerminalEnabled terminalRule w c :=
    (Finset.mem_filter.mp hc).2
  change
    UntypedDerives terminalRule binaryRule
      c.1
      (cykSlice w
        (cykLeftBoundary c.2)
        (cykRightBoundary c.2))
  rw [cykSlice_terminal]
  exact UntypedDerives.terminal hen

/-- One executable binary-candidate scan preserves chart soundness. -/
theorem cykChartStep_sound
    [Fintype N]
    [DecidableEq N]
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    [∀ A B : N, DecidablePred (binaryRule A B)]
    (w : Word α)
    (old : CYKChart N w.length)
    (hsound :
      CYKChartSound terminalRule binaryRule w old) :
    CYKChartSound terminalRule binaryRule w
      (cykChartStep binaryRule old) := by
  intro e he
  simp only [cykChartStep, Finset.mem_union] at he
  rcases he with hold | hnew
  · exact hsound e hold
  · rcases
      (mem_cykProduced_iff
        binaryRule old e).1 hnew with
      ⟨c, hen, hout⟩
    subst e
    rcases c with
      ⟨⟨A, B, C⟩, ⟨i, k, j⟩⟩
    change
      i.1 < k.1 ∧
      k.1 < j.1 ∧
      binaryRule A B C ∧
      (B, (i, k)) ∈ old ∧
      (C, (k, j)) ∈ old at hen
    rcases hen with
      ⟨hik, hkj, hbin, hleft, hright⟩
    have dleft :
        UntypedDerives terminalRule binaryRule
          B (cykSlice w i k) :=
      hsound (B, (i, k)) hleft
    have dright :
        UntypedDerives terminalRule binaryRule
          C (cykSlice w k j) :=
      hsound (C, (k, j)) hright
    have d :=
      UntypedDerives.binary hbin dleft dright
    change
      UntypedDerives terminalRule binaryRule
        A (cykSlice w i j)
    rw [cykSlice_split w i k j
      (Nat.le_of_lt hik) (Nat.le_of_lt hkj)]
    exact d

/-- Every finite executable chart iteration from the terminal seed is sound. -/
theorem cykChartIterate_sound
    [Fintype N]
    [DecidableEq N]
    (terminalRule : N → α → Prop)
    [DecidableRel terminalRule]
    (binaryRule : N → N → N → Prop)
    [∀ A B : N, DecidablePred (binaryRule A B)]
    (w : Word α) :
    ∀ r,
      CYKChartSound terminalRule binaryRule w
        (cykChartIterate binaryRule
          (cykTerminalSeed terminalRule w) r) := by
  intro r
  induction r with
  | zero =>
      exact
        cykTerminalSeed_sound
          terminalRule binaryRule w
  | succ r ih =>
      exact
        cykChartStep_sound
          terminalRule binaryRule w
          (cykChartIterate binaryRule
            (cykTerminalSeed terminalRule w) r)
          ih

end BinaryMembershipChartSound

end TCS1
end LeanCfgProject
