import LeanCfgProject.TCS1.ReconstructionSoundness

/-!
# TCS #1 v63: canonical-witness completeness

This file formalizes the combinatorial core of the v63 completeness theorem.

The manuscript first trims the full yield-typed refinement and then chooses,
for each surviving non-start typed symbol X, a canonical terminal yield
omega(X) and a canonical terminal reaching context chi(X)=(u_X,v_X).
The finite witness set contains the anchors and the terminal/binary rule
witnesses built from these choices.

Here `Active` represents the surviving symbols of the reduced typed
refinement, and `CanonicalWitnessData` packages exactly the witness
membership facts used by the completeness simulation.  No substitutability
assumption is used in this file.
-/

namespace LeanCfgProject
namespace TCS1

universe u v w

section CanonicalWitnessCompleteness

variable {α : Type u}
variable {M : Type v} [Monoid M] [Fintype M]
variable {N : Type w}

/--
Derivations in the reduced part of the full yield-typed refinement.
The predicate `Active` represents the symbols surviving trimming.
-/
inductive ReducedTypedDerives
    (H : FixedFiniteMonoidHom α M)
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (Active : N × M → Prop) :
    (N × M) → Word α → Prop
  | terminal
      {A : N} {a : α}
      (hterm : terminalRule A a)
      (hactive : Active (A, H.h [a])) :
      ReducedTypedDerives H terminalRule binaryRule Active
        (A, H.h [a]) [a]
  | binary
      {A B C : N}
      {μ ν : M}
      {wB wC : Word α}
      (hbin : binaryRule A B C)
      (hactive : Active (A, μ * ν))
      (dB : ReducedTypedDerives H terminalRule binaryRule Active
        (B, μ) wB)
      (dC : ReducedTypedDerives H terminalRule binaryRule Active
        (C, ν) wC) :
      ReducedTypedDerives H terminalRule binaryRule Active
        (A, μ * ν) (wB ++ wC)

/-- Forget trimming certificates and recover a full typed derivation. -/
theorem reducedTypedDerives_to_typedDerives
    (H : FixedFiniteMonoidHom α M)
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (Active : N × M → Prop)
    {X : N × M}
    {word : Word α}
    (d :
      ReducedTypedDerives
        H terminalRule binaryRule Active X word) :
    TypedDerives H terminalRule binaryRule X word := by
  induction d with
  | terminal hterm hactive =>
      exact TypedDerives.terminal hterm
  | @binary A B C μ ν wB wC
      hbin hactive dB dC ihB ihC =>
      exact TypedDerives.binary hbin ihB ihC

/-- Every reduced typed derivation is rooted at an active symbol. -/
theorem reducedTypedDerives_active
    (H : FixedFiniteMonoidHom α M)
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (Active : N × M → Prop)
    {X : N × M} {word : Word α}
    (d : ReducedTypedDerives H terminalRule binaryRule Active X word) :
    Active X := by
  cases d with
  | terminal _hterm hactive =>
      exact hactive
  | binary _hbin hactive _dB _dC =>
      exact hactive

/-- Yield invariant for the reduced typed refinement. -/
theorem reducedTypedDerives_yield_type
    (H : FixedFiniteMonoidHom α M)
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (Active : N × M → Prop)
    {X : N × M} {word : Word α}
    (d : ReducedTypedDerives H terminalRule binaryRule Active X word) :
    H.h word = X.2 := by
  induction d with
  | terminal _hterm _hactive =>
      rfl
  | @binary A B C μ ν wB wC _hbin _hactive _dB _dC ihB ihC =>
      rw [H.map_append wB wC, ihB, ihC]

/--
Successful start derivations of the reduced typed refinement.
The nonempty start rule is the typed copy of an untyped rule S0 -> A.
-/
inductive ReducedTypedStartDerives
    (H : FixedFiniteMonoidHom α M)
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (startRule : N → Prop)
    (epsilonStart : Prop)
    (Active : N × M → Prop) :
    Word α → Prop
  | nonempty
      {A : N} {μ : M} {word : Word α}
      (hstart : startRule A)
      (hactive : Active (A, μ))
      (d : ReducedTypedDerives H terminalRule binaryRule Active
        (A, μ) word) :
      ReducedTypedStartDerives
        H terminalRule binaryRule startRule epsilonStart Active word
  | epsilon
      (heps : epsilonStart) :
      ReducedTypedStartDerives
        H terminalRule binaryRule startRule epsilonStart Active []

/-- The language generated by the reduced typed refinement. -/
def ReducedTypedLanguage
    (H : FixedFiniteMonoidHom α M)
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (startRule : N → Prop)
    (epsilonStart : Prop)
    (Active : N × M → Prop) :
    Set (Word α) :=
  { word |
      ReducedTypedStartDerives
        H terminalRule binaryRule startRule epsilonStart Active word }

/--
The exact canonical witness information consumed by the completeness proof.
It is the logical interface of the finite set W(tilde G) from the manuscript.
-/
structure CanonicalWitnessData
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α))
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (startRule : N → Prop)
    (epsilonStart : Prop)
    (Active : N × M → Prop) where
  omega : N × M → Word α
  left : N × M → Word α
  right : N × M → Word α

  omega_ne :
    ∀ X, Active X → omega X ≠ []

  omega_type :
    ∀ X, Active X → H.h (omega X) = X.2

  anchor_mem :
    ∀ X, Active X →
      left X ++ omega X ++ right X ∈ K

  terminal_mem :
    ∀ (A : N) (a : α),
      terminalRule A a →
      Active (A, H.h [a]) →
      left (A, H.h [a]) ++ [a] ++ right (A, H.h [a]) ∈ K

  binary_mem :
    ∀ (A B C : N) (μ ν : M),
      binaryRule A B C →
      Active (A, μ * ν) →
      Active (B, μ) →
      Active (C, ν) →
      left (A, μ * ν) ++
        omega (B, μ) ++ omega (C, ν) ++
        right (A, μ * ν) ∈ K

  start_context :
    ∀ (A : N) (μ : M),
      startRule A →
      Active (A, μ) →
      left (A, μ) = [] ∧ right (A, μ) = []

  epsilon_mem :
    epsilonStart → ([] : Word α) ∈ K

/--
Canonical simulation lemma: every reduced typed derivation can be mimicked
from the canonical hypothesis nonterminal attached to its root symbol.
-/
theorem canonical_simulation
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α))
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (startRule : N → Prop)
    (epsilonStart : Prop)
    (Active : N × M → Prop)
    (D :
      CanonicalWitnessData
        H K terminalRule binaryRule startRule epsilonStart Active)
    {X : N × M}
    {word : Word α}
    (d : ReducedTypedDerives H terminalRule binaryRule Active X word) :
    HypDerives H K
      (D.omega X) (D.left X) (D.right X) word := by
  induction d with
  | @terminal A a hterm hactive =>
      let X : N × M := (A, H.h [a])
      have hanchor :
          Observed K (D.omega X) (D.left X) (D.right X) := by
        exact ⟨D.omega_ne X hactive, D.anchor_mem X hactive⟩
      have hterminal :
          Observed K [a] (D.left X) (D.right X) := by
        constructor
        · simp
        · exact D.terminal_mem A a hterm hactive
      have dlex :
          HypDerives H K [a] (D.left X) (D.right X) [a] :=
        HypDerives.r4 hterminal
      have htype : H.h (D.omega X) = H.h [a] := by
        simpa [X] using D.omega_type X hactive
      exact HypDerives.r3 hanchor hterminal htype dlex

  | @binary A B C μ ν wB wC hbin hactive dB dC ihB ihC =>
      let X : N × M := (A, μ * ν)
      let Y : N × M := (B, μ)
      let Z : N × M := (C, ν)

      have hY : Active Y := by
        simpa [Y] using
          reducedTypedDerives_active
            H terminalRule binaryRule Active dB
      have hZ : Active Z := by
        simpa [Z] using
          reducedTypedDerives_active
            H terminalRule binaryRule Active dC

      have hanchorX :
          Observed K (D.omega X) (D.left X) (D.right X) := by
        exact ⟨D.omega_ne X hactive, D.anchor_mem X hactive⟩
      have hanchorY :
          Observed K (D.omega Y) (D.left Y) (D.right Y) := by
        exact ⟨D.omega_ne Y hY, D.anchor_mem Y hY⟩
      have hanchorZ :
          Observed K (D.omega Z) (D.left Z) (D.right Z) := by
        exact ⟨D.omega_ne Z hZ, D.anchor_mem Z hZ⟩

      have hbinaryMem :
          D.left X ++ D.omega Y ++ D.omega Z ++ D.right X ∈ K := by
        simpa [X, Y, Z] using
          D.binary_mem A B C μ ν hbin hactive hY hZ

      have hbinary :
          Observed K
            (D.omega Y ++ D.omega Z)
            (D.left X) (D.right X) := by
        constructor
        · exact append_ne_nil_of_left_ne_nil (D.omega_ne Y hY)
        · simpa only [List.append_assoc] using hbinaryMem

      have hleft :
          Observed K
            (D.omega Y)
            (D.left X)
            (D.omega Z ++ D.right X) := by
        constructor
        · exact D.omega_ne Y hY
        · simpa only [List.append_assoc] using hbinaryMem

      have hright :
          Observed K
            (D.omega Z)
            (D.left X ++ D.omega Y)
            (D.right X) := by
        constructor
        · exact D.omega_ne Z hZ
        · simpa only [List.append_assoc] using hbinaryMem

      have dleft :
          HypDerives H K
            (D.omega Y)
            (D.left X)
            (D.omega Z ++ D.right X)
            wB :=
        HypDerives.r2 hleft hanchorY ihB

      have dright :
          HypDerives H K
            (D.omega Z)
            (D.left X ++ D.omega Y)
            (D.right X)
            wC :=
        HypDerives.r2 hright hanchorZ ihC

      have dbinary :
          HypDerives H K
            (D.omega Y ++ D.omega Z)
            (D.left X) (D.right X)
            (wB ++ wC) :=
        HypDerives.r1 hbinary hleft hright dleft dright

      have htype :
          H.h (D.omega X) =
            H.h (D.omega Y ++ D.omega Z) := by
        calc
          H.h (D.omega X) = μ * ν := by
            simpa [X] using D.omega_type X hactive
          _ = H.h (D.omega Y) * H.h (D.omega Z) := by
            rw [D.omega_type Y hY, D.omega_type Z hZ]
          _ = H.h (D.omega Y ++ D.omega Z) :=
            (H.map_append (D.omega Y) (D.omega Z)).symm

      exact HypDerives.r3 hanchorX hbinary htype dbinary

/--
The completeness theorem at the canonical-witness interface:
every word of the reduced typed target language is generated by the batch
reconstruction operator.
-/
theorem canonical_witness_completeness
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α))
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (startRule : N → Prop)
    (epsilonStart : Prop)
    (Active : N × M → Prop)
    (D :
      CanonicalWitnessData
        H K terminalRule binaryRule startRule epsilonStart Active) :
    ReducedTypedLanguage
      H terminalRule binaryRule startRule epsilonStart Active ⊆
      BatchLanguage H K := by
  intro word hword
  cases hword with
  | @nonempty A μ word hstart hactive d =>
      let X : N × M := (A, μ)
      have dcanon :=
        canonical_simulation
          H K terminalRule binaryRule startRule epsilonStart Active D d
      rcases D.start_context A μ hstart hactive with ⟨hleft, hright⟩
      have d0 :
          HypDerives H K (D.omega X) [] [] word := by
        simpa [X, hleft, hright] using dcanon
      have homegaK : D.omega X ∈ K := by
        have hanchor := D.anchor_mem X hactive
        simpa [X, hleft, hright] using hanchor
      exact BatchDerives.nonempty
        homegaK (D.omega_ne X hactive) d0
  | epsilon heps =>
      exact BatchDerives.epsilon (D.epsilon_mem heps)

/--
Abstract exact-reconstruction corollary.  Once the reduced typed refinement
is known to generate the target language, soundness and canonical-witness
completeness give equality.
-/
theorem exact_reconstruction_of_canonical_witnesses
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α))
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (startRule : N → Prop)
    (epsilonStart : Prop)
    (Active : N × M → Prop)
    (D :
      CanonicalWitnessData
        H K terminalRule binaryRule startRule epsilonStart Active)
    (L : Set (Word α))
    (hTarget :
      ReducedTypedLanguage
        H terminalRule binaryRule startRule epsilonStart Active = L)
    (hK : (↑K : Set (Word α)) ⊆ L)
    (hsub : FixedHSubstitutable H L) :
    BatchLanguage H K = L := by
  apply Set.Subset.antisymm
  · exact batchLanguage_sound H K L hK hsub
  · rw [← hTarget]
    exact canonical_witness_completeness
      H K terminalRule binaryRule startRule epsilonStart Active D

end CanonicalWitnessCompleteness

end TCS1
end LeanCfgProject
