import LeanCfgProject.TCS1.ConservativeGoldKernel

/-!
# TCS #1 v63: closing the no-rebuild branch of Gold convergence

ConservativeGoldKernel already proves the "first later change is exact, hence
last" branch. The manuscript has a second branch: if no rebuild occurs after
the characteristic stage, then the hypothesis present at that stage is already
exact. The reason is sample consistency plus text coverage.

This file formalizes that missing branch and packages the two cases into the
one-change dichotomy used in Corollary (Gold identification).
-/

namespace LeanCfgProject
namespace TCS1

universe u q

section GoldConvergenceClosure

variable {α : Type u}
variable {Hyp : Type q}

/--
If there are no changes from stage n0 onward, every later hypothesis object is
literally the hypothesis at stage n0.
-/
theorem hyp_constant_of_no_change
    {L : Set (Word α)}
    (R : ConservativeRun (Hyp := Hyp) L)
    (n₀ : Nat)
    (hnochange :
      ∀ n, n₀ ≤ n → R.hyp (n + 1) = R.hyp n) :
    ∀ m, n₀ ≤ m → R.hyp m = R.hyp n₀ := by
  intro m hm
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hm
  induction k with
  | zero =>
      simp
  | succ k ih =>
      have hk : n₀ ≤ n₀ + k := by omega
      calc
        R.hyp (n₀ + (k + 1)) = R.hyp ((n₀ + k) + 1) := by
          rw [Nat.add_succ]
        _ = R.hyp (n₀ + k) := hnochange (n₀ + k) hk
        _ = R.hyp n₀ := ih hk

/--
Abstract version of the manuscript's no-rebuild argument.

hsample is the invariant K_n subseteq L(H_n), and hcoverage says that every
target word eventually belongs to some accumulated sample. If there are no
changes after n0 and the current hypothesis is sound, then it is already exact.
-/
theorem exact_of_no_change_after_characteristic
    {L : Set (Word α)}
    (R : ConservativeRun (Hyp := Hyp) L)
    (n₀ : Nat)
    (hsound : R.lang (R.hyp n₀) ⊆ L)
    (hsample :
      ∀ n, (↑(R.sample n) : Set (Word α)) ⊆ R.lang (R.hyp n))
    (hcoverage :
      ∀ w, w ∈ L → ∃ n, w ∈ R.sample n)
    (hnochange :
      ∀ n, n₀ ≤ n → R.hyp (n + 1) = R.hyp n) :
    R.lang (R.hyp n₀) = L := by
  apply Set.Subset.antisymm hsound
  intro w hwL
  obtain ⟨m, hwm⟩ := hcoverage w hwL
  let q := max m n₀
  have hmq : m ≤ q := by
    exact Nat.le_max_left _ _
  have hnq : n₀ ≤ q := by
    exact Nat.le_max_right _ _
  have hwq : w ∈ R.sample q :=
    R.sample_mono hmq hwm
  have hwLangQ : w ∈ R.lang (R.hyp q) :=
    hsample q hwq
  have hconst : R.hyp q = R.hyp n₀ :=
    hyp_constant_of_no_change R n₀ hnochange q hnq
  simpa [hconst] using hwLangQ

/--
A run with genuine accumulated samples. These are exactly the extra facts
used in the paragraph K_n subseteq L(H_n) for every n of the manuscript.
-/
structure AccumulatedConservativeRun
    [DecidableEq α]
    (L : Set (Word α))
    extends ConservativeRun (α := α) (Hyp := Hyp) L where
  sample_zero :
    sample 0 = ∅

  sample_succ :
    ∀ n,
      sample (n + 1) = insert (datum (n + 1)) (sample n)

  batch_sample_consistent :
    ∀ K : Finset (Word α),
      (↑K : Set (Word α)) ⊆ lang (batch K)

/--
The accumulated sample is generated by the current hypothesis at every stage.
This is the formal induction behind K_n subseteq L(H_n) for every n.
-/
theorem accumulated_sample_generated
    [DecidableEq α]
    {L : Set (Word α)}
    (R : AccumulatedConservativeRun (Hyp := Hyp) L) :
    ∀ n, (↑(R.sample n) : Set (Word α)) ⊆ R.lang (R.hyp n) := by
  intro n
  induction n with
  | zero =>
      intro w hw
      have hempty : w ∈ (∅ : Finset (Word α)) := by
        simpa [R.sample_zero] using hw
      simpa using hempty

  | succ n ih =>
      by_cases hgen :
          R.datum (n + 1) ∈ R.lang (R.hyp n)
      · have hkeep :
            R.hyp (n + 1) = R.hyp n :=
          R.keep_if_generated n hgen
        intro w hw
        have hwInsert :
            w ∈ insert (R.datum (n + 1)) (R.sample n) := by
          simpa [R.sample_succ n] using hw
        rcases Finset.mem_insert.mp hwInsert with hdatum | hold
        · subst w
          simpa [hkeep] using hgen
        · have hwOld : w ∈ R.lang (R.hyp n) :=
            ih hold
          simpa [hkeep] using hwOld

      · have hrebuild :
            R.hyp (n + 1) = R.batch (R.sample (n + 1)) :=
          R.rebuild_if_missing n hgen
        intro w hw
        rw [hrebuild]
        exact R.batch_sample_consistent (R.sample (n + 1)) hw

/--
Concrete no-change branch for accumulated positive-data runs.
-/
theorem exact_of_no_change_for_accumulated_run
    [DecidableEq α]
    {L : Set (Word α)}
    (R : AccumulatedConservativeRun (Hyp := Hyp) L)
    (n₀ : Nat)
    (hsound : R.lang (R.hyp n₀) ⊆ L)
    (hcoverage :
      ∀ w, w ∈ L → ∃ n, w ∈ R.sample n)
    (hnochange :
      ∀ n, n₀ ≤ n → R.hyp (n + 1) = R.hyp n) :
    R.lang (R.hyp n₀) = L := by
  exact
    exact_of_no_change_after_characteristic
      R.toConservativeRun n₀ hsound
      (accumulated_sample_generated R)
      hcoverage hnochange

/--
The two branches of the Gold proof, packaged exactly as a one-change
dichotomy after the characteristic stage.

Either the stage-n0 hypothesis is already exact and remains fixed, or there is
a later change; that new hypothesis is exact and remains fixed forever.
-/
theorem gold_one_change_dichotomy
    [DecidableEq α]
    {L : Set (Word α)}
    (R : AccumulatedConservativeRun (Hyp := Hyp) L)
    (C : Finset (Word α))
    (n₀ : Nat)
    (hC : C ⊆ R.sample n₀)
    (hbatch :
      ∀ m,
        C ⊆ R.sample m →
        R.lang (R.batch (R.sample m)) = L)
    (hsound : R.lang (R.hyp n₀) ⊆ L)
    (hcoverage :
      ∀ w, w ∈ L → ∃ n, w ∈ R.sample n) :
    (R.lang (R.hyp n₀) = L ∧
      ∀ k, R.hyp (n₀ + k) = R.hyp n₀)
    ∨
    (∃ n,
      n₀ ≤ n ∧
      R.hyp (n + 1) ≠ R.hyp n ∧
      R.lang (R.hyp (n + 1)) = L ∧
      ∀ k, R.hyp ((n + 1) + k) = R.hyp (n + 1)) := by
  classical
  by_cases hchange :
      ∃ n, n₀ ≤ n ∧ R.hyp (n + 1) ≠ R.hyp n
  · right
    obtain ⟨n, hn, hneq⟩ := hchange
    have hexact :
        R.lang (R.hyp (n + 1)) = L :=
      exact_after_post_characteristic_change
        R.toConservativeRun C n₀ n hC hn hbatch hneq
    have hstable :
        ∀ k, R.hyp ((n + 1) + k) = R.hyp (n + 1) :=
      stable_from_exact R.toConservativeRun (n + 1) hexact
    exact ⟨n, hn, hneq, hexact, hstable⟩

  · left
    have hnochange :
        ∀ n, n₀ ≤ n → R.hyp (n + 1) = R.hyp n := by
      intro n hn
      by_contra hneq
      exact hchange ⟨n, hn, hneq⟩
    have hexact :
        R.lang (R.hyp n₀) = L :=
      exact_of_no_change_for_accumulated_run
        R n₀ hsound hcoverage hnochange
    exact
      ⟨hexact,
        stable_from_exact R.toConservativeRun n₀ hexact⟩

end GoldConvergenceClosure

end TCS1
end LeanCfgProject
