import LeanCfgProject.TCS1.TerminalIsolationKernel

/-!
# TCS #1 v65: least-closed CFG semantics and terminal-isolation preservation

This file lifts the local terminal-isolation equations to a full grammar
language statement. Rather than relying on an implementation-specific parse
tree representation, generated nonterminal languages are presented
denotationally as the least family of terminal languages closed under all
grammar rules.

For the isolated grammar, every fresh wrapper is forced to contain its
one-letter word. Restricting any closed isolated interpretation to the old
nonterminals is therefore closed for the source grammar; conversely, extending
any closed source interpretation with the exact wrapper languages yields a
closed isolated interpretation. This Galois-style pair proves equality of the
least generated languages on all old nonterminals.
-/

namespace LeanCfgProject
namespace TCS1

universe u v

section LeastClosedCFGLanguage

variable {N : Type u}
variable {α : Type v}

/-- A family of nonterminal languages closed under one grammar-rule step. -/
def GrammarClosed
    (R : MixedRules N α)
    (L : N → Set (List α)) : Prop :=
  ∀ A, RuleStepLanguage R L A ⊆ L A

/--
The least closed language generated by one nonterminal, defined as the
intersection of all closed interpretations.
-/
def LeastClosedLanguage
    (R : MixedRules N α)
    (A : N) :
    Set (List α) :=
  {w | ∀ L, GrammarClosed R L → w ∈ L A}

/-- RHS realization is monotone in the interpretation of nonterminals. -/
theorem rhsRealizes_mono
    {L₁ L₂ : N → Set (List α)}
    (hsub : ∀ A, L₁ A ⊆ L₂ A)
    {rhs : List (MixedSymbol N α)}
    {w : List α}
    (h : RhsRealizes L₁ rhs w) :
    RhsRealizes L₂ rhs w := by
  induction rhs generalizing w with
  | nil =>
      exact h
  | cons s rhs ih =>
      cases s with
      | inr a =>
          rcases h with ⟨tail, hw, htail⟩
          exact ⟨tail, hw, ih htail⟩
      | inl A =>
          rcases h with ⟨u, v, hw, hu, hv⟩
          exact ⟨u, v, hw, hsub A hu, ih hv⟩

/-- The one-step grammar operator is monotone in child languages. -/
theorem ruleStepLanguage_mono
    (R : MixedRules N α)
    {L₁ L₂ : N → Set (List α)}
    (hsub : ∀ A, L₁ A ⊆ L₂ A)
    (A : N) :
    RuleStepLanguage R L₁ A ⊆
      RuleStepLanguage R L₂ A := by
  intro w hw
  rcases hw with ⟨rhs, hR, hreal⟩
  exact ⟨rhs, hR, rhsRealizes_mono hsub hreal⟩

/--
Extending a closed source interpretation by exact one-letter wrapper
languages produces a closed interpretation of the isolated grammar.
-/
theorem isolatedInterpretation_closed
    (R : MixedRules N α)
    (L : N → Set (List α))
    (hclosed : GrammarClosed R L) :
    GrammarClosed
      (IsolatedRule R)
      (isolatedInterpretation L) := by
  intro X w hw
  cases X with
  | inl A =>
      have heq := terminalIsolation_ruleStep_eq R L A
      have hs : w ∈ RuleStepLanguage R L A := by
        rw [← heq]
        exact hw
      exact hclosed A hs
  | inr a =>
      have heq := terminalIsolation_wrapper_ruleStep R L a
      have hs : w ∈ ({[a]} : Set (List α)) := by
        rw [← heq]
        exact hw
      simpa [isolatedInterpretation] using hs

/-- Every closed isolated interpretation contains the intended wrapper word. -/
theorem wrapper_word_mem_of_closed
    (R : MixedRules N α)
    (Q : (N ⊕ α) → Set (List α))
    (hclosed : GrammarClosed (IsolatedRule R) Q)
    (a : α) :
    [a] ∈ Q (Sum.inr a) := by
  apply hclosed (Sum.inr a)
  refine ⟨[Sum.inr a], IsolatedRule.wrapper a, ?_⟩
  exact ⟨[], rfl, rfl⟩

/-- Restriction of an isolated interpretation to the old nonterminals. -/
def restrictIsolated
    (Q : (N ⊕ α) → Set (List α)) :
    N → Set (List α) :=
  fun A => Q (Sum.inl A)

/--
The exact extension of the old-state restriction is contained in every
closed isolated interpretation.
-/
theorem isolatedInterpretation_restrict_subset
    (R : MixedRules N α)
    (Q : (N ⊕ α) → Set (List α))
    (hclosed : GrammarClosed (IsolatedRule R) Q) :
    ∀ X,
      isolatedInterpretation (restrictIsolated Q) X ⊆ Q X := by
  intro X w hw
  cases X with
  | inl A =>
      exact hw
  | inr a =>
      have hwEq : w = [a] := by
        simpa [isolatedInterpretation] using hw
      subst w
      exact wrapper_word_mem_of_closed R Q hclosed a

/--
Restricting any closed isolated interpretation to the old nonterminals gives
a closed interpretation of the source grammar.
-/
theorem restrictIsolated_closed
    (R : MixedRules N α)
    (Q : (N ⊕ α) → Set (List α))
    (hclosed : GrammarClosed (IsolatedRule R) Q) :
    GrammarClosed R (restrictIsolated Q) := by
  intro A w hw
  have heq :
      RuleStepLanguage
          (IsolatedRule R)
          (isolatedInterpretation (restrictIsolated Q))
          (Sum.inl A)
        =
      RuleStepLanguage R (restrictIsolated Q) A :=
    terminalIsolation_ruleStep_eq R (restrictIsolated Q) A
  have hwExt :
      w ∈ RuleStepLanguage
        (IsolatedRule R)
        (isolatedInterpretation (restrictIsolated Q))
        (Sum.inl A) := by
    rw [heq]
    exact hw
  have hsub :
      ∀ X,
        isolatedInterpretation (restrictIsolated Q) X ⊆ Q X :=
    isolatedInterpretation_restrict_subset R Q hclosed
  have hwQ :
      w ∈ RuleStepLanguage (IsolatedRule R) Q (Sum.inl A) :=
    ruleStepLanguage_mono (IsolatedRule R) hsub (Sum.inl A) hwExt
  exact hclosed (Sum.inl A) hwQ

/--
Terminal isolation preserves the full least-generated language of every old
nonterminal.
-/
theorem terminalIsolation_leastClosedLanguage_eq
    (R : MixedRules N α)
    (A : N) :
    LeastClosedLanguage (IsolatedRule R) (Sum.inl A)
      =
    LeastClosedLanguage R A := by
  apply Set.ext
  intro w
  constructor
  · intro hwTarget
    intro L hL
    have hIso :
        GrammarClosed (IsolatedRule R) (isolatedInterpretation L) :=
      isolatedInterpretation_closed R L hL
    have hw := hwTarget (isolatedInterpretation L) hIso
    exact hw
  · intro hwSource
    intro Q hQ
    have hRestr : GrammarClosed R (restrictIsolated Q) :=
      restrictIsolated_closed R Q hQ
    exact hwSource (restrictIsolated Q) hRestr

/--
The fresh wrapper state has exactly the singleton generated language {[a]}.
-/
theorem terminalIsolation_wrapper_leastClosed_eq_singleton
    (R : MixedRules N α)
    (a : α) :
    LeastClosedLanguage (IsolatedRule R) (Sum.inr a)
      =
    ({[a]} : Set (List α)) := by
  apply Set.ext
  intro w
  constructor
  · intro hw
    let Ltop : N → Set (List α) := fun _ => Set.univ
    have htop : GrammarClosed R Ltop := by
      intro A u hu
      trivial
    have hIso :
        GrammarClosed (IsolatedRule R) (isolatedInterpretation Ltop) :=
      isolatedInterpretation_closed R Ltop htop
    have hw' := hw (isolatedInterpretation Ltop) hIso
    simpa [isolatedInterpretation] using hw'
  · intro hw
    have hwEq : w = [a] := by
      simpa using hw
    subst w
    intro Q hQ
    exact wrapper_word_mem_of_closed R Q hQ a

end LeastClosedCFGLanguage

end TCS1
end LeanCfgProject
