import LeanCfgProject.TCS1.LinearNormalizationRules
import LeanCfgProject.TCS1.PreparedLinearGrammarSemantics
import LeanCfgProject.TCS1.YieldTypedRefinementCore
import Mathlib.Tactic

/-!
# TCS #1: semantic soundness of the concrete linear-spine construction

This file proves the reverse language inclusion for the concrete normalization:
every terminal word derived by an old state of the factorized terminal/binary
grammar is already generated by the corresponding prepared linear
nonterminal.

The proof uses the canonical residual interpretation of every fresh chain
state.  An auxiliary state after step i denotes the suffix of the spine plan
beginning at step i+1.  Source closure then makes this interpretation closed
under every generated terminal and binary rule.

A later module proves the converse inclusion by explicitly executing each
finite spine plan.
-/

namespace LeanCfgProject
namespace TCS1

universe u v w

section LinearNormalizationSoundness

variable {N : Type u}
variable {α : Type v}
variable {P : Type w}

/-- Residual language represented after k outer spine steps have been emitted. -/
def LinearPlanResidualLanguage
    (L : N → Set (List α))
    (plan : PreparedLinearPlan N α)
    (k : Nat) :
    Set (List α) :=
  {word |
    ∃ endpointWord,
      LinearPlanEndpoint.realizes L
        plan.endpoint endpointWord
      ∧
      word =
        applyLinearSpineSteps
          (plan.steps.drop k) endpointWord}

/--
Canonical interpretation of every concrete normalized state over an
interpretation of the old source nonterminals.
-/
def LinearConstructedInterpretation
    (G : PreparedLinearIndexedCFG N α P)
    (L : N → Set (List α)) :
    LinearConstructedState G → Set (List α)
  | Sum.inl A =>
      L A
  | Sum.inr (Sum.inl a) =>
      {word | word = [a]}
  | Sum.inr (Sum.inr aux) =>
      LinearPlanResidualLanguage L
        (G.rhs aux.1).toPlan
        (aux.2.1 + 1)

/-- Closure interface for a terminal/binary non-start grammar. -/
structure LinearTerminalBinaryClosed
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (L : N → Set (List α)) : Prop where
  terminal :
    ∀ {A : N} {a : α},
      terminalRule A a →
      [a] ∈ L A
  binary :
    ∀ {A B C : N}
      {left right : List α},
      binaryRule A B C →
      left ∈ L B →
      right ∈ L C →
      left ++ right ∈ L A

/-- Every explicit terminal/binary derivation belongs to every closed family. -/
theorem untypedDerives_mem_of_linearClosed
    {X : Type*}
    {β : Type*}
    (terminalRule : X → β → Prop)
    (binaryRule : X → X → X → Prop)
    (L : X → Set (List β))
    (hclosed :
      LinearTerminalBinaryClosed
        terminalRule binaryRule L)
    {A : X}
    {word : List β}
    (d :
      UntypedDerives
        terminalRule binaryRule A word) :
    word ∈ L A := by
  induction d with
  | terminal hterm =>
      exact hclosed.terminal hterm
  | binary hbin dB dC ihB ihC =>
      exact hclosed.binary hbin ihB ihC

/-- Old states retain exactly the supplied source interpretation. -/
@[simp] theorem linearOldState_mem_iff
    (G : PreparedLinearIndexedCFG N α P)
    (L : N → Set (List α))
    (A : N)
    (word : List α) :
    word ∈
        LinearConstructedInterpretation G L
          (linearOldState G A)
      ↔
    word ∈ L A := by
  rfl

/-- Auxiliary state i denotes precisely the residual plan after step i. -/
theorem linearAuxState_mem_iff
    (G : PreparedLinearIndexedCFG N α P)
    (L : N → Set (List α))
    (p : P)
    (i : Fin (G.rhs p).toPlan.steps.length)
    (word : List α) :
    word ∈
        LinearConstructedInterpretation G L
          (linearAuxState G p i)
      ↔
    word ∈
        LinearPlanResidualLanguage L
          (G.rhs p).toPlan (i.1 + 1) := by
  rfl

/--
Membership of a planned continuing child is exactly the residual language
after the current step.
-/
theorem linearStepContinuation_mem_iff_residual
    (G : PreparedLinearIndexedCFG N α P)
    (L : N → Set (List α))
    (p : P)
    (i : Fin (G.rhs p).toPlan.steps.length)
    (word : List α) :
    word ∈
        LinearConstructedInterpretation G L
          (linearStepContinuation G p i)
      ↔
    word ∈
        LinearPlanResidualLanguage L
          (G.rhs p).toPlan (i.1 + 1) := by
  cases hend : (G.rhs p).toPlan.endpoint with
  | terminal a =>
      have hcont :
          linearStepContinuation G p i =
            linearAuxState G p i := by
        simp [linearStepContinuation, hend]
      rw [hcont]
      exact linearAuxState_mem_iff G L p i word
  | core B =>
      by_cases hnext :
          i.1 + 1 < (G.rhs p).toPlan.steps.length
      · have hcont :
            linearStepContinuation G p i =
              linearAuxState G p i := by
          simp [linearStepContinuation, hend, hnext]
        rw [hcont]
        exact linearAuxState_mem_iff G L p i word
      · have heq :
            i.1 + 1 =
              (G.rhs p).toPlan.steps.length := by
          omega
        have hcont :
            linearStepContinuation G p i =
              linearOldState G B := by
          exact
            linearStepContinuation_eq_core_of_last
              G p i B hend heq
        rw [hcont, linearOldState_mem_iff]
        unfold LinearPlanResidualLanguage
        rw [hend, heq]
        simp [LinearPlanEndpoint.realizes,
          applyLinearSpineSteps]

/--
Away from the first step, a planned step parent denotes the residual language
beginning at that step.
-/
theorem linearStepParent_mem_iff_residual
    (G : PreparedLinearIndexedCFG N α P)
    (L : N → Set (List α))
    (p : P)
    (i : Fin (G.rhs p).toPlan.steps.length)
    (hpos : i.1 ≠ 0)
    (word : List α) :
    word ∈
        LinearConstructedInterpretation G L
          (linearStepParent G p i)
      ↔
    word ∈
        LinearPlanResidualLanguage L
          (G.rhs p).toPlan i.1 := by
  have hidx :
      i.1 - 1 + 1 = i.1 := by
    omega
  unfold linearStepParent
  rw [dif_neg hpos]
  rw [linearAuxState_mem_iff]
  simpa [hidx]

/--
The canonical residual interpretation is closed under all concrete factorized
rules whenever the old-state family is closed under the source spine plans.
-/
theorem linearConstructedInterpretation_closed
    (G : PreparedLinearIndexedCFG N α P)
    (L : N → Set (List α))
    (hsource :
      PreparedLinearPlanClosed G L) :
    LinearTerminalBinaryClosed
      (LinearConstructedTerminalRule G)
      (LinearConstructedBinaryRule G)
      (LinearConstructedInterpretation G L) := by
  refine
    { terminal := ?_
      binary := ?_ }
  · intro A a hterm
    cases hterm with
    | wrapper a =>
        rfl
    | sourceEndpoint p a hend hsteps =>
        change [a] ∈ L (G.lhs p)
        apply hsource p [a]
        refine ⟨[a], ?_, ?_⟩
        · rw [hend]
          rfl
        · rw [hsteps]
          rfl
    | auxEndpoint p a i hend hlast =>
        change
          [a] ∈
            LinearPlanResidualLanguage L
              (G.rhs p).toPlan (i.1 + 1)
        refine ⟨[a], ?_, ?_⟩
        · rw [hend]
          rfl
        · rw [hlast]
          simp [applyLinearSpineSteps]
  · intro A B C left right hbin hleft hright
    cases hbin with
    | left p i hside =>
        change left = [(linearPlanStep G p i).terminal] at hleft
        have hcont :
            right ∈
              LinearPlanResidualLanguage L
                (G.rhs p).toPlan (i.1 + 1) :=
          (linearStepContinuation_mem_iff_residual
            G L p i right).1 hright
        rcases hcont with
          ⟨endpointWord, hendpoint, hrightEq⟩
        have hstep :
            left ++ right =
              applyLinearSpineSteps
                ((G.rhs p).toPlan.steps.drop i.1)
                endpointWord := by
          rw [hleft]
          calc
            [(linearPlanStep G p i).terminal] ++ right
                =
              (linearPlanStep G p i).apply right := by
                simp [LinearSpineStep.apply, hside]
            _ =
              (linearPlanStep G p i).apply
                (applyLinearSpineSteps
                  ((G.rhs p).toPlan.steps.drop (i.1 + 1))
                  endpointWord) := by
                    rw [← hrightEq]
            _ =
              applyLinearSpineSteps
                ((G.rhs p).toPlan.steps.drop i.1)
                endpointWord := by
                  exact
                    (applyLinearSpineSteps_drop_get
                      (G.rhs p).toPlan.steps i endpointWord).symm
        by_cases hzero : i.1 = 0
        · rw [linearStepParent_zero G p i hzero]
          change left ++ right ∈ L (G.lhs p)
          apply hsource p (left ++ right)
          refine ⟨endpointWord, hendpoint, ?_⟩
          simpa [hzero] using hstep
        · apply
            (linearStepParent_mem_iff_residual
              G L p i hzero (left ++ right)).2
          exact ⟨endpointWord, hendpoint, hstep⟩
    | right p i hside =>
        change right = [(linearPlanStep G p i).terminal] at hright
        have hcont :
            left ∈
              LinearPlanResidualLanguage L
                (G.rhs p).toPlan (i.1 + 1) :=
          (linearStepContinuation_mem_iff_residual
            G L p i left).1 hleft
        rcases hcont with
          ⟨endpointWord, hendpoint, hleftEq⟩
        have hstep :
            left ++ right =
              applyLinearSpineSteps
                ((G.rhs p).toPlan.steps.drop i.1)
                endpointWord := by
          rw [hright]
          calc
            left ++ [(linearPlanStep G p i).terminal]
                =
              (linearPlanStep G p i).apply left := by
                simp [LinearSpineStep.apply, hside]
            _ =
              (linearPlanStep G p i).apply
                (applyLinearSpineSteps
                  ((G.rhs p).toPlan.steps.drop (i.1 + 1))
                  endpointWord) := by
                    rw [← hleftEq]
            _ =
              applyLinearSpineSteps
                ((G.rhs p).toPlan.steps.drop i.1)
                endpointWord := by
                  exact
                    (applyLinearSpineSteps_drop_get
                      (G.rhs p).toPlan.steps i endpointWord).symm
        by_cases hzero : i.1 = 0
        · rw [linearStepParent_zero G p i hzero]
          change left ++ right ∈ L (G.lhs p)
          apply hsource p (left ++ right)
          refine ⟨endpointWord, hendpoint, ?_⟩
          simpa [hzero] using hstep
        · apply
            (linearStepParent_mem_iff_residual
              G L p i hzero (left ++ right)).2
          exact ⟨endpointWord, hendpoint, hstep⟩

/--
Semantic soundness of the concrete factorization on every old nonterminal.
-/
theorem linearConstructed_old_derives_to_prepared
    (G : PreparedLinearIndexedCFG N α P)
    {A : N}
    {word : List α}
    (d :
      UntypedDerives
        (LinearConstructedTerminalRule G)
        (LinearConstructedBinaryRule G)
        (linearOldState G A) word) :
    PreparedLinearDerives G A word := by
  have hplanClosed :
      PreparedLinearPlanClosed G
        (PreparedLinearLanguage G) :=
    (preparedLinearGrammarClosed_iff_planClosed
      G (PreparedLinearLanguage G)).1
      (preparedLinearLanguage_closed G)
  have hclosed :=
    linearConstructedInterpretation_closed
      G (PreparedLinearLanguage G) hplanClosed
  have hmem :=
    untypedDerives_mem_of_linearClosed
      (LinearConstructedTerminalRule G)
      (LinearConstructedBinaryRule G)
      (LinearConstructedInterpretation G
        (PreparedLinearLanguage G))
      hclosed d
  exact hmem

end LinearNormalizationSoundness

end TCS1
end LeanCfgProject
