import LeanCfgProject.TCS1.LinearNormalizationSize
import Mathlib.Tactic

/-!
# TCS #1: exact spine plans for linear normalization

This module turns the case distinction in Appendix
"Proof of the linear-spine SSBNF normalization" into a small semantic plan.

For a prepared rule A -> u B v, the top-down continuing spine emits

  * the terminals of u from left to right as left wrapper children, then
  * the terminals of v from right to left as right wrapper children,

and finally reaches B.  This is exactly the order of the J- and R-chains in
the appendix.

For a terminal-only rule A -> a_1 ... a_m, the first m-1 terminals are emitted
as left wrappers and the final fresh non-wrapper chain symbol has the terminal
rule -> a_m.

The plan layer is independent of the eventual finite names assigned to fresh
chain states.  It records the semantic content that the concrete rule
construction must implement.
-/

namespace LeanCfgProject
namespace TCS1

universe u v

section LinearNormalizationPlan

variable {N : Type u}
variable {α : Type v}

/-- Which side of the continuing spine carries one terminal wrapper. -/
inductive LinearSpineSide
  | left
  | right
deriving DecidableEq, Repr

/-- One terminal-emitting binary spine step. -/
structure LinearSpineStep (α : Type v) where
  side : LinearSpineSide
  terminal : α

/-- Apply one spine step to the word generated by its continuing child. -/
def LinearSpineStep.apply
    (s : LinearSpineStep α)
    (word : List α) :
    List α :=
  match s.side with
  | .left => s.terminal :: word
  | .right => word ++ [s.terminal]

/--
Execute a top-down spine plan.  The head step is the outermost binary rule.
-/
def applyLinearSpineSteps :
    List (LinearSpineStep α) → List α → List α
  | [], word => word
  | step :: rest, word =>
      step.apply (applyLinearSpineSteps rest word)


/--
At any valid position, executing the dropped plan exposes exactly the indexed
step followed by the next dropped suffix.
-/
theorem applyLinearSpineSteps_drop_get
    (steps : List (LinearSpineStep α))
    (i : Fin steps.length)
    (word : List α) :
    applyLinearSpineSteps
        (steps.drop i.1) word
      =
    (steps.get i).apply
      (applyLinearSpineSteps
        (steps.drop (i.1 + 1)) word) := by
  rw [← List.cons_get_drop_succ (l := steps) (n := i)]
  rfl

/-- Left-wrapper steps associated with a terminal list. -/
def leftLinearSteps
    (xs : List α) :
    List (LinearSpineStep α) :=
  xs.map (fun a =>
    { side := .left, terminal := a })

/--
Right-wrapper steps are traversed from the outside inward, so the terminals of
the right context occur in reverse order along the top-down spine.
-/
def rightLinearSteps
    (xs : List α) :
    List (LinearSpineStep α) :=
  xs.reverse.map (fun a =>
    { side := .right, terminal := a })

@[simp] theorem apply_leftLinearSteps
    (xs : List α)
    (word : List α) :
    applyLinearSpineSteps
        (leftLinearSteps xs) word
      =
    xs ++ word := by
  induction xs with
  | nil =>
      simp [leftLinearSteps, applyLinearSpineSteps]
  | cons a rest ih =>
      have hcons :=
        congrArg (List.cons a) ih
      simpa [leftLinearSteps,
        applyLinearSpineSteps,
        LinearSpineStep.apply] using hcons

/-- Executing concatenated plan fragments is sequential composition. -/
theorem applyLinearSpineSteps_append
    (xs ys : List (LinearSpineStep α))
    (word : List α) :
    applyLinearSpineSteps (xs ++ ys) word =
      applyLinearSpineSteps xs
        (applyLinearSpineSteps ys word) := by
  induction xs with
  | nil =>
      rfl
  | cons step rest ih =>
      simp [applyLinearSpineSteps, ih]

/-- Right-oriented steps in direct list order append the reversed list. -/
theorem apply_rightMappedLinearSteps
    (xs : List α)
    (word : List α) :
    applyLinearSpineSteps
        (xs.map (fun a =>
          { side := LinearSpineSide.right,
            terminal := a })) word
      =
    word ++ xs.reverse := by
  induction xs with
  | nil =>
      simp [applyLinearSpineSteps]
  | cons a rest ih =>
      simp [applyLinearSpineSteps,
        LinearSpineStep.apply, ih,
        List.append_assoc]

/--
Executing reversed right-wrapper steps restores the original right-context
order in the generated terminal word.
-/
@[simp] theorem apply_rightLinearSteps
    (xs : List α)
    (word : List α) :
    applyLinearSpineSteps
        (rightLinearSteps xs) word
      =
    word ++ xs := by
  unfold rightLinearSteps
  rw [apply_rightMappedLinearSteps]
  simp

/-- The exact top-down spine plan for a rule u B v. -/
def aroundLinearSteps
    (left right : List α) :
    List (LinearSpineStep α) :=
  leftLinearSteps left ++ rightLinearSteps right

/--
The appendix J/R chain generates exactly u z v when its continuing endpoint B
generates z.
-/
theorem apply_aroundLinearSteps
    (left right : List α)
    (word : List α) :
    applyLinearSpineSteps
        (aroundLinearSteps left right) word
      =
    left ++ word ++ right := by
  unfold aroundLinearSteps
  rw [applyLinearSpineSteps_append]
  rw [apply_rightLinearSteps]
  rw [apply_leftLinearSteps]
  simp [List.append_assoc]

@[simp] theorem leftLinearSteps_length
    (xs : List α) :
    (leftLinearSteps xs).length = xs.length := by
  simp [leftLinearSteps]

@[simp] theorem rightLinearSteps_length
    (xs : List α) :
    (rightLinearSteps xs).length = xs.length := by
  simp [rightLinearSteps]

@[simp] theorem aroundLinearSteps_length
    (left right : List α) :
    (aroundLinearSteps left right).length =
      left.length + right.length := by
  simp [aroundLinearSteps]

/--
Terminal-only factorization plan.

The returned step list emits every terminal except the last one as a left
wrapper; the returned terminal labels the final non-wrapper terminal rule.
-/
def terminalLinearPlan :
    α → List α → List (LinearSpineStep α) × α
  | head, [] =>
      ([], head)
  | head, next :: rest =>
      ({ side := .left, terminal := head } ::
          (terminalLinearPlan next rest).1,
        (terminalLinearPlan next rest).2)

/--
Executing the terminal-only plan down to its final terminal reproduces the
source terminal word exactly.
-/
theorem terminalLinearPlan_apply
    (head : α)
    (tail : List α) :
    applyLinearSpineSteps
        (terminalLinearPlan head tail).1
        [(terminalLinearPlan head tail).2]
      =
    head :: tail := by
  induction tail generalizing head with
  | nil =>
      simp [terminalLinearPlan, applyLinearSpineSteps]
  | cons next rest ih =>
      have htail := ih next
      have hcons :=
        congrArg (List.cons head) htail
      simpa [terminalLinearPlan,
        applyLinearSpineSteps,
        LinearSpineStep.apply] using hcons

/-- The terminal-only plan has exactly m-1 binary spine steps. -/
theorem terminalLinearPlan_steps_length
    (head : α)
    (tail : List α) :
    (terminalLinearPlan head tail).1.length =
      tail.length := by
  induction tail generalizing head with
  | nil =>
      rfl
  | cons next rest ih =>
      simp [terminalLinearPlan, ih]

/-- Endpoint of one prepared linear normalization plan. -/
inductive LinearPlanEndpoint
    (N : Type u)
    (α : Type v)
  | core (A : N)
  | terminal (a : α)

/-- Exact semantic spine plan attached to one prepared RHS. -/
structure PreparedLinearPlan
    (N : Type u)
    (α : Type v) where
  steps : List (LinearSpineStep α)
  endpoint : LinearPlanEndpoint N α

/-- Convert the appendix's two prepared RHS forms to one uniform spine plan. -/
def PreparedLinearRhs.toPlan :
    PreparedLinearRhs N α → PreparedLinearPlan N α
  | .terminals head tail =>
      let plan := terminalLinearPlan head tail
      { steps := plan.1
        endpoint := .terminal plan.2 }
  | .around left core right nonunit =>
      { steps := aroundLinearSteps left right
        endpoint := .core core }

/-- Semantic word supplied by the endpoint of a plan. -/
def LinearPlanEndpoint.realizes
    (L : N → Set (List α)) :
    LinearPlanEndpoint N α → List α → Prop
  | .core A, word =>
      word ∈ L A
  | .terminal a, word =>
      word = [a]

/-- Semantic realization of a prepared RHS before normalization. -/
def PreparedLinearRhs.realizes
    (L : N → Set (List α)) :
    PreparedLinearRhs N α → List α → Prop
  | .terminals head tail, word =>
      word = head :: tail
  | .around left core right nonunit, word =>
      ∃ z,
        z ∈ L core ∧
        word = left ++ z ++ right

/--
Uniform plan semantics: execute the wrapper steps around a word realized by
the endpoint.
-/
def PreparedLinearPlan.realizes
    (L : N → Set (List α))
    (plan : PreparedLinearPlan N α)
    (word : List α) : Prop :=
  ∃ endpointWord,
    LinearPlanEndpoint.realizes L
      plan.endpoint endpointWord
    ∧
    word =
      applyLinearSpineSteps
        plan.steps endpointWord

/--
The plan extracted from a prepared linear RHS has exactly the same semantic
realizations as that source RHS.
-/
theorem preparedLinearRhs_realizes_iff_plan
    (L : N → Set (List α))
    (rhs : PreparedLinearRhs N α)
    (word : List α) :
    PreparedLinearRhs.realizes L rhs word
      ↔
    PreparedLinearPlan.realizes L rhs.toPlan word := by
  cases rhs with
  | terminals head tail =>
      constructor
      · intro hword
        change word = head :: tail at hword
        refine
          ⟨[(terminalLinearPlan head tail).2],
            rfl, ?_⟩
        change word =
          applyLinearSpineSteps
            (terminalLinearPlan head tail).1
            [(terminalLinearPlan head tail).2]
        rw [terminalLinearPlan_apply]
        exact hword
      · rintro ⟨endpointWord, hend, hword⟩
        change endpointWord =
          [(terminalLinearPlan head tail).2] at hend
        change word =
          applyLinearSpineSteps
            (terminalLinearPlan head tail).1
            endpointWord at hword
        rw [hend, terminalLinearPlan_apply] at hword
        change word = head :: tail
        exact hword
  | around left core right nonunit =>
      constructor
      · intro hsource
        change ∃ z,
          z ∈ L core ∧
          word = left ++ z ++ right at hsource
        rcases hsource with ⟨z, hz, hword⟩
        refine ⟨z, hz, ?_⟩
        change word =
          applyLinearSpineSteps
            (aroundLinearSteps left right) z
        rw [apply_aroundLinearSteps]
        exact hword
      · rintro ⟨z, hz, hword⟩
        change z ∈ L core at hz
        change word =
          applyLinearSpineSteps
            (aroundLinearSteps left right) z at hword
        change ∃ z,
          z ∈ L core ∧
          word = left ++ z ++ right
        refine ⟨z, hz, ?_⟩
        rw [apply_aroundLinearSteps] at hword
        exact hword

/--
The plan-step count is the appendix's exact binary-rule count for the prepared
RHS.
-/
theorem PreparedLinearRhs.toPlan_steps_length
    (rhs : PreparedLinearRhs N α) :
    rhs.toPlan.steps.length =
      rhs.binaryCount := by
  cases rhs with
  | terminals head tail =>
      simp [PreparedLinearRhs.toPlan,
        PreparedLinearRhs.binaryCount,
        terminalLinearPlan_steps_length]
  | around left core right nonunit =>
      simp [PreparedLinearRhs.toPlan,
        PreparedLinearRhs.binaryCount]

/--
For u B v, the non-unit preprocessing guarantee implies a nonempty spine plan.
-/
theorem aroundLinearSteps_nonempty_of_nonunit
    (left right : List α)
    (hnonunit : left ≠ [] ∨ right ≠ []) :
    aroundLinearSteps left right ≠ [] := by
  intro hnil
  have hlen :
      (aroundLinearSteps left right).length = 0 := by
    rw [hnil]
    rfl
  rw [aroundLinearSteps_length] at hlen
  rcases hnonunit with hleft | hright
  · have hpos : 0 < left.length := by
      cases left with
      | nil =>
          exact False.elim (hleft rfl)
      | cons a rest =>
          simp
    omega
  · have hpos : 0 < right.length := by
      cases right with
      | nil =>
          exact False.elim (hright rfl)
      | cons a rest =>
          simp
    omega

/--
The appendix's exact auxiliary-state count is never larger than the number of
binary spine steps.  Terminal-only plans use one auxiliary state per step;
around plans use one fewer auxiliary state because the final step continues
directly to the old core nonterminal.
-/
theorem PreparedLinearRhs.toPlan_auxCount_le_steps
    (rhs : PreparedLinearRhs N α) :
    rhs.auxCount ≤ rhs.toPlan.steps.length := by
  cases rhs with
  | terminals head tail =>
      simp [PreparedLinearRhs.auxCount,
        PreparedLinearRhs.terminalCount,
        PreparedLinearRhs.toPlan_steps_length,
        PreparedLinearRhs.binaryCount]
  | around left core right hnonunit =>
      rw [PreparedLinearRhs.toPlan_steps_length]
      simp only [PreparedLinearRhs.auxCount,
        PreparedLinearRhs.terminalCount,
        PreparedLinearRhs.binaryCount]
      omega

/--
Plan rule count is the number of binary steps plus one iff the endpoint is a
terminal.  This equals the expansion rule count from the size kernel.
-/
theorem PreparedLinearRhs.toPlan_ruleCount
    (rhs : PreparedLinearRhs N α) :
    rhs.toPlan.steps.length +
        (match rhs.toPlan.endpoint with
         | .core _ => 0
         | .terminal _ => 1)
      =
    rhs.expansionRuleCount := by
  cases rhs with
  | terminals head tail =>
      simp [PreparedLinearRhs.toPlan,
        PreparedLinearRhs.expansionRuleCount,
        PreparedLinearRhs.binaryCount,
        PreparedLinearRhs.localTerminalCount,
        terminalLinearPlan_steps_length]
  | around left core right nonunit =>
      simp [PreparedLinearRhs.toPlan,
        PreparedLinearRhs.expansionRuleCount,
        PreparedLinearRhs.binaryCount,
        PreparedLinearRhs.localTerminalCount]

end LinearNormalizationPlan

end TCS1
end LeanCfgProject
