import LeanCfgProject.TCS1.LinearRawEpsilonUnitSemantics

/-!
# TCS #1: semantic facade for arbitrary indexed linear CFG preprocessing

This module composes the raw representation theorem with the explicit
epsilon/unit elimination semantics.

For an ordinary finite indexed linear CFG, no "already preprocessed" premise
is needed semantically:

* epsilon membership is recorded exactly by raw nullability;
* every nonempty source word is generated by the unit-free linear grammar
  exactly when it belongs to the original least closed language.

This is the semantic left-hand bridge needed before turning the unit-free rule
family into the finite prepared grammar consumed by the specialized
linear-spine normalization.
-/

namespace LeanCfgProject
namespace TCS1

universe u v w

section LinearRawPreprocessingFacade

variable {N : Type u}
variable {α : Type v}
variable {P : Type w}

/-- Raw nullability is exactly epsilon membership in the original source CFG. -/
theorem indexedLinear_rawNullable_iff_source_epsilon
    (G : IndexedMixedCFG N α P)
    (hlinear : G.IsLinear)
    (A : N) :
    RawLinearNullable (G.toRawLinear hlinear) A
      ↔
    [] ∈ LeastClosedLanguage G.toMixedRules A := by
  unfold RawLinearNullable
  rw [rawLinearDerives_iff_least]
  rw [indexedMixedCFG_rawLeast_eq_source]

/--
Every nonempty word is preserved exactly from the original indexed linear CFG
through raw epsilon and unit elimination.
-/
theorem indexedLinear_unitFree_iff_source_nonempty
    (G : IndexedMixedCFG N α P)
    (hlinear : G.IsLinear)
    (A : N)
    (word : List α)
    (hne : word ≠ []) :
    RawLinearUnitFreeDerives
        (G.toRawLinear hlinear) A word
      ↔
    word ∈ LeastClosedLanguage G.toMixedRules A := by
  calc
    RawLinearUnitFreeDerives
        (G.toRawLinear hlinear) A word
      ↔
    RawLinearDerives
        (G.toRawLinear hlinear) A word :=
      (rawLinear_preprocessing_preserves_nonempty
        (G.toRawLinear hlinear) A word hne).symm
    _ ↔
      word ∈ RawLinearLeastLanguage
        (G.toRawLinear hlinear) A :=
      rawLinearDerives_iff_least
        (G.toRawLinear hlinear) A word
    _ ↔
      word ∈ LeastClosedLanguage G.toMixedRules A := by
      rw [indexedMixedCFG_rawLeast_eq_source
        G hlinear A]

/--
Separated semantic target after raw preprocessing: epsilon is retained
explicitly, while every nonempty word is generated by the unit-free grammar.
-/
def IndexedMixedCFG.rawLinearPreprocessedLanguage
    (G : IndexedMixedCFG N α P)
    (hlinear : G.IsLinear)
    (S : N) :
    Set (List α) :=
  {word |
    (RawLinearNullable (G.toRawLinear hlinear) S ∧ word = [])
      ∨
    RawLinearUnitFreeDerives
      (G.toRawLinear hlinear) S word}

/--
The separated epsilon/unit-free target is exactly the original source
language, including epsilon.
-/
theorem indexedLinear_rawPreprocessedLanguage_eq_source
    (G : IndexedMixedCFG N α P)
    (hlinear : G.IsLinear)
    (S : N) :
    G.rawLinearPreprocessedLanguage hlinear S
      =
    LeastClosedLanguage G.toMixedRules S := by
  apply Set.ext
  intro word
  constructor
  · intro hword
    rcases hword with heps | hnonempty
    · rcases heps with ⟨hnull, rfl⟩
      exact
        (indexedLinear_rawNullable_iff_source_epsilon
          G hlinear S).1 hnull
    · have hne :
          word ≠ [] :=
        rawLinearEpsilonFreeDerives_nonempty
          (G.toRawLinear hlinear)
          ((rawLinear_unit_elimination_preserves_language
            (G.toRawLinear hlinear) S word).2 hnonempty)
      exact
        (indexedLinear_unitFree_iff_source_nonempty
          G hlinear S word hne).1 hnonempty
  · intro hsource
    by_cases heq : word = []
    · left
      refine ⟨?_, heq⟩
      subst word
      exact
        (indexedLinear_rawNullable_iff_source_epsilon
          G hlinear S).2 hsource
    · right
      exact
        (indexedLinear_unitFree_iff_source_nonempty
          G hlinear S word heq).2 hsource

end LinearRawPreprocessingFacade

end TCS1
end LeanCfgProject
