import LeanCfgProject.TCS1.DyckOneBracketKernel
import LeanCfgProject.TCS1.FixedHRightQuotient

/-!
# TCS #1 v78: Lukasiewicz boundary witness

Section 9 uses the Lukasiewicz language generated by S -> a S S | b and the
identity L_Luk = D1 b.  The fixed-word quotient lemma then gives

  L_Luk / b = D1,

so any fixed-h substitutability of L_Luk would force fixed-h
substitutability of D1, contradicting the Dyck obstruction theorem.

This file formalizes that semantic quotient argument.  The separate standard
fact that the Lukasiewicz language is deterministic context-free is not
needed for the quotient contradiction itself and is not claimed here.
-/

namespace LeanCfgProject
namespace TCS1
namespace Lukasiewicz

open DyckOne
open DyckOne.Symbol

/-- The semantic form D1 b used in the manuscript. -/
def Language : Set (Word DyckOne.Symbol) :=
  {w | ∃ x : Word DyckOne.Symbol,
    x ∈ DyckOne.Language ∧
    w = x ++ [b]}

/-- Membership is exactly "a Dyck word followed by one final b". -/
theorem mem_iff
    (w : Word DyckOne.Symbol) :
    w ∈ Language ↔
      ∃ x : Word DyckOne.Symbol,
        x ∈ DyckOne.Language ∧
        w = x ++ [b] := by
  rfl

/-- Right quotient of D1 b by b is exactly D1. -/
theorem rightQuotient_b_eq_dyck :
    FixedRightQuotient Language [b] =
      DyckOne.Language := by
  apply Set.ext
  intro w
  constructor
  · intro hw
    change w ++ [b] ∈ Language at hw
    rcases hw with ⟨x, hx, hEq⟩
    have hwx : w = x := by
      exact List.append_cancel_right hEq
    simpa [hwx] using hx
  · intro hw
    change w ++ [b] ∈ Language
    exact ⟨w, hw, rfl⟩

/--
For every fixed finite-monoid typing, the Lukasiewicz language is not
fixed-h substitutable.
-/
theorem not_fixedH
    {M : Type*} [Monoid M] [Fintype M]
    (H : FixedFiniteMonoidHom
      DyckOne.Symbol M) :
    ¬ FixedHSubstitutable H Language := by
  intro hLuk
  have hquot :
      FixedHSubstitutable H
        (FixedRightQuotient Language [b]) :=
    fixedHSubstitutable_fixedRightQuotient
      H Language [b] hLuk
  rw [rightQuotient_b_eq_dyck] at hquot
  exact DyckOne.not_fixedH H hquot

/--
Paper-facing form of the fixed-word quotient contradiction used immediately
before the Clark comparison proposition.
-/
theorem fixedWordQuotient_boundary_contradiction
    {M : Type*} [Monoid M] [Fintype M]
    (H : FixedFiniteMonoidHom
      DyckOne.Symbol M) :
    FixedHSubstitutable H Language →
      FixedHSubstitutable H DyckOne.Language := by
  intro hLuk
  have hquot :=
    fixedHSubstitutable_fixedRightQuotient
      H Language [b] hLuk
  simpa [rightQuotient_b_eq_dyck] using hquot

end Lukasiewicz
end TCS1
end LeanCfgProject
