import LeanCfgProject.TCS1.UnitFreeReachableTrim

/-!
# TCS #1 v66: fresh separated start and optional empty word

SSBNF requires one fresh start symbol S0 that never occurs on a right-hand
side.  Its rules are only S0 -> A and, when the language contains the empty
word, S0 -> lambda.  All non-start rules are terminal or binary.

The complete productive/reachability trim from UnitFreeReachableTrim already
has only terminal and binary rules.  This file adds the fresh start explicitly
using Option: none is the new start, while some A embeds a final trimmed state.

A single induction on derivations proves the exact start language:

  L(S0) = L(oldStart) union ({lambda} if keepEmpty).

Thus the last start-separation step of Appendix A is now semantic, not merely
an informal convention.
-/

namespace LeanCfgProject
namespace TCS1

universe u v

section SeparatedStartSSBNF

variable {N : Type u}
variable {α : Type v}

/-- State type with none reserved for the fresh separated start. -/
abbrev SeparatedStartState
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G) :=
  Option (ReducedUnitFreeState G start)

/--
Fresh-start grammar.  Non-start states inherit only terminal/binary rules;
the fresh start has one unit rule to the old start and an optional epsilon
rule.
-/
def separatedStartGrammar
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop) :
    BinaryNullableGrammar
      (SeparatedStartState G start) α where
  terminalRule X a :=
    match X with
    | none => False
    | some A =>
        (reducedUnitFreeGrammar G start).terminalRule A a
  binaryRule X Y Z :=
    match X, Y, Z with
    | some A, some B, some C =>
        (reducedUnitFreeGrammar G start).binaryRule A B C
    | _, _, _ => False
  epsilonRule X :=
    match X with
    | none => keepEmpty
    | some _ => False
  unitRule X Y :=
    match X, Y with
    | none, some A =>
        A = reducedUnitFreeStart G start
    | _, _ => False

/-- Lift any final-trim derivation under the some embedding. -/
theorem reducedDerives_to_separated
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    {A : ReducedUnitFreeState G start}
    {w : List α}
    (d : BinaryNullableDerives
      (reducedUnitFreeGrammar G start) A w) :
    BinaryNullableDerives
      (separatedStartGrammar G start keepEmpty)
      (some A) w := by
  induction d with
  | terminal h =>
      exact BinaryNullableDerives.terminal h
  | epsilon h =>
      exact False.elim h
  | unit h _ _ =>
      exact False.elim h
  | @binary A B C wB wC h _ _ ihB ihC =>
      have h' :
          (separatedStartGrammar G start keepEmpty).binaryRule
            (some A) (some B) (some C) := by
        simpa [separatedStartGrammar] using h
      exact BinaryNullableDerives.binary h' ihB ihC

/--
Shape theorem for every separated-start derivation.  At none, a derivation is
either the optional empty word or a word generated by the old reduced start;
at some A it is exactly a derivation from A in the final trimmed grammar.
-/
theorem separatedStart_derivation_shape
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    {X : SeparatedStartState G start}
    {w : List α}
    (d : BinaryNullableDerives
      (separatedStartGrammar G start keepEmpty) X w) :
    match X with
    | none =>
        (w = [] ∧ keepEmpty) ∨
          BinaryNullableDerives
            (reducedUnitFreeGrammar G start)
            (reducedUnitFreeStart G start) w
    | some A =>
        BinaryNullableDerives
          (reducedUnitFreeGrammar G start) A w := by
  induction d with
  | @terminal X a h =>
      cases X with
      | none =>
          exact False.elim h
      | some A =>
          exact BinaryNullableDerives.terminal h
  | @epsilon X h =>
      cases X with
      | none =>
          exact Or.inl ⟨rfl, h⟩
      | some A =>
          exact False.elim h
  | @unit X Y w h d ih =>
      cases X with
      | some A =>
          exact False.elim h
      | none =>
          cases Y with
          | none =>
              exact False.elim h
          | some B =>
              have hB :
                  B = reducedUnitFreeStart G start :=
                h
              subst B
              exact Or.inr ih
  | @binary X Y Z wY wZ h dY dZ ihY ihZ =>
      cases X with
      | none =>
          exact False.elim h
      | some A =>
          cases Y with
          | none =>
              exact False.elim h
          | some B =>
              cases Z with
              | none =>
                  exact False.elim h
              | some C =>
                  exact
                    BinaryNullableDerives.binary
                      h ihY ihZ

/-- The optional start epsilon rule derives lambda exactly when requested. -/
theorem separatedStart_derives_empty
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    {keepEmpty : Prop}
    (hEmpty : keepEmpty) :
    BinaryNullableDerives
      (separatedStartGrammar G start keepEmpty)
      none [] :=
  BinaryNullableDerives.epsilon hEmpty

/-- Every old-start derivation lifts through the unique fresh-start unit rule. -/
theorem reducedStartDerives_to_separatedStart
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    {w : List α}
    (d : BinaryNullableDerives
      (reducedUnitFreeGrammar G start)
      (reducedUnitFreeStart G start) w) :
    BinaryNullableDerives
      (separatedStartGrammar G start keepEmpty)
      none w := by
  have hunit :
      (separatedStartGrammar G start keepEmpty).unitRule
        none
        (some (reducedUnitFreeStart G start)) := by
    rfl
  exact
    BinaryNullableDerives.unit hunit
      (reducedDerives_to_separated
        G start keepEmpty d)

/-- Exact generated language of the fresh separated start. -/
theorem separatedStart_language_iff
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (w : List α) :
    BinaryNullableDerives
        (separatedStartGrammar G start keepEmpty)
        none w
      ↔
    (w = [] ∧ keepEmpty) ∨
      BinaryNullableDerives
        (reducedUnitFreeGrammar G start)
        (reducedUnitFreeStart G start) w := by
  constructor
  · intro d
    exact
      separatedStart_derivation_shape
        G start keepEmpty d
  · intro h
    rcases h with hEmpty | hOld
    · rcases hEmpty with ⟨rfl, hk⟩
      exact separatedStart_derives_empty G start hk
    · exact
        reducedStartDerives_to_separatedStart
          G start keepEmpty hOld

/--
Equivalent start-language statement directly against the ambient unit-free
language before the final productive/reachability trim.
-/
theorem separatedStart_language_iff_unitFree
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (w : List α) :
    BinaryNullableDerives
        (separatedStartGrammar G start keepEmpty)
        none w
      ↔
    (w = [] ∧ keepEmpty) ∨
      UnitFreeDerives G start.1 w := by
  rw [separatedStart_language_iff]
  constructor
  · intro h
    rcases h with hEmpty | hOld
    · exact Or.inl hEmpty
    · exact Or.inr
        ((reducedStart_language_iff_unitFree
          G start w).1 hOld)
  · intro h
    rcases h with hEmpty | hOld
    · exact Or.inl hEmpty
    · exact Or.inr
        ((reducedStart_language_iff_unitFree
          G start w).2 hOld)

/-- The fresh start has no terminal rule. -/
theorem separatedStart_no_terminal_rule
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (a : α) :
    ¬ (separatedStartGrammar G start keepEmpty).terminalRule none a := by
  simp [separatedStartGrammar]

/-- The fresh start has no binary rule. -/
theorem separatedStart_no_binary_rule
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (B C : SeparatedStartState G start) :
    ¬ (separatedStartGrammar G start keepEmpty).binaryRule none B C := by
  simp [separatedStartGrammar]

/-- Non-start states have no epsilon rules. -/
theorem separatedStart_nonstart_no_epsilon
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (A : ReducedUnitFreeState G start) :
    ¬ (separatedStartGrammar G start keepEmpty).epsilonRule (some A) := by
  simp [separatedStartGrammar]

/-- Non-start states have no unit rules. -/
theorem separatedStart_nonstart_no_unit
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (A : ReducedUnitFreeState G start)
    (B : SeparatedStartState G start) :
    ¬ (separatedStartGrammar G start keepEmpty).unitRule (some A) B := by
  cases B <;> simp [separatedStartGrammar]

/--
The fresh start can never occur as a binary child, so it never appears on a
right-hand side of a non-start binary rule.
-/
theorem separatedStart_never_binary_child
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (A B : SeparatedStartState G start) :
    ¬ (separatedStartGrammar G start keepEmpty).binaryRule A none B
    ∧
    ¬ (separatedStartGrammar G start keepEmpty).binaryRule A B none := by
  cases A <;> cases B <;>
    simp [separatedStartGrammar]

/--
The only possible unit target is some oldStart, never the fresh start; hence
the fresh start never occurs on a unit-rule right-hand side either.
-/
theorem separatedStart_never_unit_target
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (keepEmpty : Prop)
    (A : SeparatedStartState G start) :
    ¬ (separatedStartGrammar G start keepEmpty).unitRule A none := by
  cases A <;> simp [separatedStartGrammar]

end SeparatedStartSSBNF

end TCS1
end LeanCfgProject
