import LeanCfgProject.TCS1.UnitFreeProductiveTrim

/-!
# TCS #1 v66: concrete reachability trim from a designated start

The productive trim keeps exactly states having terminal yields.  A reduced CFG
also keeps only states reachable from the designated start.  This module
formalizes that second half of the final trim.

Reachability is generated by binary child edges of the productive unit-free
grammar.  We restrict again to the subtype of reachable productive states.
Every derivation rooted at a reachable state lifts to the restricted grammar,
because every child used by a binary rule is reachable in one more step.

Consequently the final restricted grammar:

* has exactly the same terminal language at the designated start;
* has no epsilon or unit rules;
* has only terminal and binary rules;
* every retained state is productive; and
* every retained state is reachable from the designated start by construction.

This is the concrete semantic reducedness layer missing from the earlier
abstract final-trim interface.  Preservation of lambda, when the source
language contains the empty word, is handled separately by the start rule.
-/

namespace LeanCfgProject
namespace TCS1

universe u v

section UnitFreeReachableTrim

variable {N : Type u}
variable {α : Type v}

/-- Reachability through binary-rule child edges from the designated start. -/
inductive ProductiveUnitFreeReachable
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G) :
    ProductiveUnitFreeState G → Prop
  | start :
      ProductiveUnitFreeReachable G start start
  | left
      {A B C : ProductiveUnitFreeState G}
      (hA : ProductiveUnitFreeReachable G start A)
      (h :
        (productiveUnitFreeGrammar G).binaryRule A B C) :
      ProductiveUnitFreeReachable G start B
  | right
      {A B C : ProductiveUnitFreeState G}
      (hA : ProductiveUnitFreeReachable G start A)
      (h :
        (productiveUnitFreeGrammar G).binaryRule A B C) :
      ProductiveUnitFreeReachable G start C

/-- Productive states that are reachable from the designated start. -/
abbrev ReducedUnitFreeState
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G) :=
  {A : ProductiveUnitFreeState G //
    ProductiveUnitFreeReachable G start A}

/--
Final terminal/binary grammar after restricting the productive grammar to
states reachable from the start.
-/
def reducedUnitFreeGrammar
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G) :
    BinaryNullableGrammar
      (ReducedUnitFreeState G start) α where
  terminalRule A a :=
    (productiveUnitFreeGrammar G).terminalRule A.1 a
  binaryRule A B C :=
    (productiveUnitFreeGrammar G).binaryRule A.1 B.1 C.1
  epsilonRule _ :=
    False
  unitRule _ _ :=
    False

/-- The designated start as a state of the final reduced grammar. -/
def reducedUnitFreeStart
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G) :
    ReducedUnitFreeState G start :=
  ⟨start, ProductiveUnitFreeReachable.start⟩

/-- Forgetting reachability annotations maps final derivations back. -/
theorem reducedTrimDerives_to_productive
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    {A : ReducedUnitFreeState G start}
    {w : List α}
    (d : BinaryNullableDerives
      (reducedUnitFreeGrammar G start) A w) :
    BinaryNullableDerives
      (productiveUnitFreeGrammar G) A.1 w := by
  induction d with
  | terminal h =>
      exact BinaryNullableDerives.terminal h
  | epsilon h =>
      exact False.elim h
  | unit h _ _ =>
      exact False.elim h
  | binary h _ _ ihB ihC =>
      exact BinaryNullableDerives.binary h ihB ihC

/--
Every productive-grammar derivation rooted at a reachable state lifts to the
final reduced grammar.
-/
theorem productiveDerives_to_reducedTrim
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    {A : ProductiveUnitFreeState G}
    {w : List α}
    (hA : ProductiveUnitFreeReachable G start A)
    (d : BinaryNullableDerives
      (productiveUnitFreeGrammar G) A w) :
    BinaryNullableDerives
      (reducedUnitFreeGrammar G start)
      (⟨A, hA⟩ : ReducedUnitFreeState G start)
      w := by
  induction d with
  | @terminal A a h =>
      exact BinaryNullableDerives.terminal h
  | @epsilon A h =>
      exact False.elim h
  | @unit A B w h d ih =>
      exact False.elim h
  | @binary A B C wB wC h dB dC ihB ihC =>
      have hB :
          ProductiveUnitFreeReachable G start B :=
        ProductiveUnitFreeReachable.left hA h
      have hC :
          ProductiveUnitFreeReachable G start C :=
        ProductiveUnitFreeReachable.right hA h
      let B' : ReducedUnitFreeState G start :=
        ⟨B, hB⟩
      let C' : ReducedUnitFreeState G start :=
        ⟨C, hC⟩
      have h' :
          (reducedUnitFreeGrammar G start).binaryRule
            (⟨A, hA⟩ : ReducedUnitFreeState G start)
            B' C' := by
        exact h
      exact
        BinaryNullableDerives.binary h'
          (ihB hB)
          (ihC hC)

/-- Exact language preservation on every retained reachable productive state. -/
theorem reducedTrimDerives_iff_productive
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (A : ReducedUnitFreeState G start)
    (w : List α) :
    BinaryNullableDerives
        (reducedUnitFreeGrammar G start) A w
      ↔
    BinaryNullableDerives
        (productiveUnitFreeGrammar G) A.1 w := by
  constructor
  · exact reducedTrimDerives_to_productive G start
  · intro d
    exact
      productiveDerives_to_reducedTrim
        G start A.2 d

/-- The designated start language is unchanged by the reachability trim. -/
theorem reducedStart_language_iff_productiveStart
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (w : List α) :
    BinaryNullableDerives
        (reducedUnitFreeGrammar G start)
        (reducedUnitFreeStart G start) w
      ↔
    BinaryNullableDerives
        (productiveUnitFreeGrammar G) start w := by
  exact
    reducedTrimDerives_iff_productive
      G start (reducedUnitFreeStart G start) w

/-- The designated start language also equals the ambient unit-free language. -/
theorem reducedStart_language_iff_unitFree
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (w : List α) :
    BinaryNullableDerives
        (reducedUnitFreeGrammar G start)
        (reducedUnitFreeStart G start) w
      ↔
    UnitFreeDerives G start.1 w := by
  rw [reducedStart_language_iff_productiveStart]
  exact productiveTrimDerives_iff_unitFree G start w

/-- No epsilon rule survives the complete productive/reachability trim. -/
theorem reducedUnitFreeGrammar_no_epsilon
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (A : ReducedUnitFreeState G start) :
    ¬ (reducedUnitFreeGrammar G start).epsilonRule A := by
  simp [reducedUnitFreeGrammar]

/-- No unit rule survives the complete productive/reachability trim. -/
theorem reducedUnitFreeGrammar_no_unit
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (A B : ReducedUnitFreeState G start) :
    ¬ (reducedUnitFreeGrammar G start).unitRule A B := by
  simp [reducedUnitFreeGrammar]

/-- Every state retained by the complete trim is productive in the final grammar. -/
theorem reducedUnitFreeGrammar_all_productive
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G) :
    ∀ A : ReducedUnitFreeState G start,
      ∃ w,
        BinaryNullableDerives
          (reducedUnitFreeGrammar G start) A w := by
  intro A
  obtain ⟨w, hwAmbient⟩ := A.1.2
  have hwProductive :
      BinaryNullableDerives
        (productiveUnitFreeGrammar G) A.1 w :=
    (productiveTrimDerives_iff_unitFree
      G A.1 w).2 hwAmbient
  exact
    ⟨w,
      (reducedTrimDerives_iff_productive
        G start A w).2 hwProductive⟩

/-- Every retained state is reachable from the designated start by definition. -/
theorem reducedUnitFreeGrammar_all_reachable
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (A : ReducedUnitFreeState G start) :
    ProductiveUnitFreeReachable G start A.1 :=
  A.2

/-- Every terminal word generated by the final reduced grammar is nonempty. -/
theorem reducedTrimDerives_nonempty
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    {A : ReducedUnitFreeState G start}
    {w : List α}
    (d : BinaryNullableDerives
      (reducedUnitFreeGrammar G start) A w) :
    w ≠ [] := by
  have hp :
      BinaryNullableDerives
        (productiveUnitFreeGrammar G) A.1 w :=
    reducedTrimDerives_to_productive
      G start d
  exact productiveTrimDerives_nonempty G hp

/-- Uniform shortest-yield bounds survive the complete final trim unchanged. -/
theorem yieldBound_reducedTrim
    (G : BinaryNullableGrammar N α)
    (start : ProductiveUnitFreeState G)
    (b : Nat)
    (hbound :
      YieldBound
        (fun A => {w | UnitFreeDerives G A w})
        b) :
    YieldBound
      (fun A : ReducedUnitFreeState G start =>
        {w | BinaryNullableDerives
          (reducedUnitFreeGrammar G start) A w})
      b := by
  intro A
  obtain ⟨w, hw, hlen⟩ :=
    hbound A.1.1
  have hwProductive :
      BinaryNullableDerives
        (productiveUnitFreeGrammar G) A.1 w :=
    (productiveTrimDerives_iff_unitFree
      G A.1 w).2 hw
  exact
    ⟨w,
      (reducedTrimDerives_iff_productive
        G start A w).2 hwProductive,
      hlen⟩

end UnitFreeReachableTrim

end TCS1
end LeanCfgProject
