import LeanCfgProject.TCS1.YieldTypedRefinementCore

/-!
# TCS #1 v117: exponential typed-thickness gap, core derivations

This proves the exact typed-one yield for the E_i fragment of the displayed
G_i^c grammar. A later finite indexed-SSBNF bridge must still establish
whole-grammar reducedness, source size, source thickness, and preservation
under the productive/reachable typed trim. By itself this is NOT the
complete source Proposition prop:typed-thickness-gap.
-/

namespace LeanCfgProject
namespace TCS1

inductive V117GapLetter where
  | a
  | c
  deriving DecidableEq, Fintype, Repr

inductive V117GapType where
  | one
  | zero
  deriving DecidableEq, Fintype, Repr

instance : Monoid V117GapType where
  one := .one
  mul x y := match x with
    | .one => y
    | .zero => .zero
  one_mul := by intro x; rfl
  mul_one := by intro x; cases x <;> rfl
  mul_assoc := by intro x y z; cases x <;> rfl

def v117GapLetterType : V117GapLetter → V117GapType
  | .a => .one
  | .c => .zero

def v117GapWordType : Word V117GapLetter → V117GapType
  | [] => .one
  | a :: w => v117GapLetterType a * v117GapWordType w

theorem v117GapWordType_append
    (u v : Word V117GapLetter) :
    v117GapWordType (u ++ v) =
      v117GapWordType u * v117GapWordType v := by
  induction u with
  | nil => rfl
  | cons a u ih =>
      simp [v117GapWordType, ih, mul_assoc]

/-- Exactly the fixed two-element monoid typing in the source argument. -/
def v117GapHom : FixedFiniteMonoidHom V117GapLetter V117GapType where
  h := v117GapWordType
  map_nil := rfl
  map_append := v117GapWordType_append

/-- A word is of type one iff it contains no c. -/
theorem v117GapWordType_one_iff
    (w : Word V117GapLetter) :
    v117GapWordType w = .one ↔ V117GapLetter.c ∉ w := by
  induction w with
  | nil => simp [v117GapWordType]
  | cons b w ih =>
      cases b with
      | a =>
          have hsame :
              v117GapWordType (V117GapLetter.a :: w) =
                v117GapWordType w := by
            cases h : v117GapWordType w <;> rfl
          simpa [hsame] using ih
      | c =>
          have hzero :
              v117GapWordType (V117GapLetter.c :: w) =
                V117GapType.zero := by
            cases h : v117GapWordType w <;> rfl
          simp [hzero]

/-- Explicit doubling prevents the general simplifier from unfolding replicates. -/
private theorem v117GapPowSucc (i : Nat) :
    2 ^ (i + 1) = 2 ^ i + 2 ^ i := by
  rw [pow_succ]
  omega

/-- Exactly the E_i rules: E_0 -> a and E_(i+1) -> E_i E_i | c. -/
inductive V117GapEDerives : Nat → Word V117GapLetter → Prop
  | base : V117GapEDerives 0 [.a]
  | shortcut {i : Nat} : V117GapEDerives (i + 1) [.c]
  | branch {i : Nat} {u v : Word V117GapLetter}
      (left : V117GapEDerives i u)
      (right : V117GapEDerives i v) :
      V117GapEDerives (i + 1) (u ++ v)

/-- Every type-one E_i yield is the exponentially long all-a word. -/
theorem v117GapEDerives_no_c_exact
    {i : Nat} {w : Word V117GapLetter}
    (d : V117GapEDerives i w) :
    V117GapLetter.c ∉ w →
      w = List.replicate (2 ^ i) .a := by
  induction d with
  | base => intro _; rfl
  | @shortcut i =>
      intro hnc
      exfalso
      exact hnc (by simp)
  | @branch i u v left right ihl ihr =>
      intro hnc
      have hl : V117GapLetter.c ∉ u := by
        intro h
        exact hnc (List.mem_append.mpr (Or.inl h))
      have hr : V117GapLetter.c ∉ v := by
        intro h
        exact hnc (List.mem_append.mpr (Or.inr h))
      rw [ihl hl, ihr hr]
      rw [v117GapPowSucc i, List.replicate_add]

/-- The all-a word of length 2^i is generated by E_i. -/
theorem v117GapEDerives_all_a
    (i : Nat) :
    V117GapEDerives i (List.replicate (2 ^ i) .a) := by
  induction i with
  | zero => simpa using V117GapEDerives.base
  | succ i ih =>
      change V117GapEDerives (i + 1)
        (List.replicate (2 ^ (i + 1)) .a)
      rw [v117GapPowSucc i, List.replicate_add]
      exact V117GapEDerives.branch ih ih

/-- Ordinary source thickness of every E_i is one. -/
theorem v117GapEDerives_short_yield
    (i : Nat) :
    ∃ w : Word V117GapLetter,
      V117GapEDerives i w ∧ w.length = 1 := by
  cases i with
  | zero => exact ⟨[.a], V117GapEDerives.base, rfl⟩
  | succ i => exact ⟨[.c], V117GapEDerives.shortcut, rfl⟩

/-- Under the fixed two-element typing, E_i at type one has unique yield. -/
theorem v117GapEDerives_type_one_exact
    {i : Nat} {w : Word V117GapLetter}
    (d : V117GapEDerives i w)
    (ht : v117GapHom.h w = 1) :
    w = List.replicate (2 ^ i) .a := by
  exact v117GapEDerives_no_c_exact d
    ((v117GapWordType_one_iff w).mp ht)

/-- Such a type-one derivation exists, with length exactly 2^i. -/
theorem v117GapEDerives_type_one_exists
    (i : Nat) :
    ∃ w : Word V117GapLetter,
      V117GapEDerives i w ∧
      v117GapHom.h w = 1 ∧
      w.length = 2 ^ i := by
  refine ⟨List.replicate (2 ^ i) .a,
    v117GapEDerives_all_a i, ?_, by simp⟩
  apply (v117GapWordType_one_iff _).2
  simp

end TCS1
end LeanCfgProject
