import LeanCfgProject.TCS1.V128ThicknessGapProposition

/-!
# TCS #1 v128: fixed-h substitutability of the gap example's target

The actual finite indexed G_n grammar generates {a,c}^+, so it generates a
context-free language. This language is fixed-h substitutable under the
fixed two-element typing h_c (indeed under *any* word typing): all nonempty
internal factors have the full two-sided distribution. This supplies the
remaining semantic target-class fact used by the displayed example in
Proposition prop:typed-thickness-gap.

No separate closure-theorem assumption is required.
-/

namespace LeanCfgProject
namespace TCS1

private theorem gap_append_middle_nonempty
    (u x v : List Bool) (hx : x ≠ []) :
    u ++ x ++ v ≠ [] := by
  intro hnil
  have hlen := congrArg List.length hnil
  have hpos : 0 < x.length := by
    cases x with
    | nil => exact False.elim (hx rfl)
    | cons a xs => simp
  simp only [List.length_append, List.length_nil] at hlen
  omega

/-- Positive words are substitutable for any finite-monoid typing. -/
theorem gapPositiveWords_fixedHSubstitutable
    {M : Type} [Monoid M] [Fintype M]
    (H : FixedFiniteMonoidHom Bool M) :
    FixedHSubstitutable H {w : List Bool | w ≠ []} := by
  intro x y hx hy _heq _hshared
  apply Set.ext
  intro c
  change
    (c.1 ++ x ++ c.2 ≠ []) ↔
      (c.1 ++ y ++ c.2 ≠ [])
  exact ⟨fun _ => gap_append_middle_nonempty c.1 y c.2 hy,
    fun _ => gap_append_middle_nonempty c.1 x c.2 hx⟩

/-- The source language of every G_n lies in the fixed h_c substitutable
    CFL family: it is generated by the displayed finite SSBNF grammar
    and satisfies the fixed-h distributional property. -/
theorem gapSource_fixedHSubstitutable (n : Nat) :
    FixedHSubstitutable gapCZeroTyping
      (UntypedStartLanguage (GapTerminalRule n)
        (GapBinaryRule n) (GapStartRule n) False) := by
  rw [gapSource_startLanguage_eq_nonempty n]
  exact gapPositiveWords_fixedHSubstitutable gapCZeroTyping


/-- Complete single-instance statement combining the source's h_c-class
    membership with the earlier reducedness, ordinary/typed thickness
    separation, and explicit linear grammar-size certificate. -/
theorem v128_exponential_gap_manuscript_instance (n : Nat) :
    FixedHSubstitutable gapCZeroTyping
      (UntypedStartLanguage (GapTerminalRule n)
        (GapBinaryRule n) (GapStartRule n) False) ∧
    (UntypedStartLanguage (GapTerminalRule n) (GapBinaryRule n)
        (GapStartRule n) False =
      {w : List Bool | w ≠ []}) ∧
    (∀ A : GapNonterminal n,
      GapSourceReachable n A ∧
        ∃ w : List Bool,
          UntypedDerives (GapTerminalRule n) (GapBinaryRule n) A w) ∧
    (YieldBound (gapSourceYieldLanguage n) 1 ∧
      ∀ bound : Nat,
        YieldBound (gapSourceYieldLanguage n) bound →
        1 ≤ bound) ∧
    (∀ bound : Nat,
      YieldBound (gapRetainedTypedYieldLanguage n) bound →
      2 ^ n ≤ bound) ∧
    (gapSourceGrammarSymbolBudget n ≤ 34 * (n + 1)) := by
  exact ⟨gapSource_fixedHSubstitutable n,
    v128_exponential_typed_thickness_gap_package n⟩

end TCS1
end LeanCfgProject
