import LeanCfgProject.TCS1.V128SubstringBucketEntryBound

/-!
# TCS #1 v128: concrete finite enumeration of context/type buckets

This is a delta from the already checked v88 two-cut occurrence space.

The set of candidate bucket keys is the image of the **existing**
finite ReconstructionFactorSlot space under the map
  (sample, cut1, cut2) |-> (leftContext, rightContext, h(factor)).
Unused, reversed and empty-factor slots may add harmless empty buckets.

Every v116 unary relation x ~ y is covered: its common observed
context (p,q) supplies a canonical occurrence slot, and both
x and y belong to the bucket with key ((p,q),h(x)).

Combining the earlier bucket-entry injection with this explicit key
set proves the cubic number of all ordered in-bucket pairs, without
assuming a finite collection of keys externally.

This is a bound on the unary candidate **enumeration**, not yet a
complete certified O(n_K^4) literal CFG output encoder or a runtime
cost semantics for computing the monoid homomorphism.
-/

namespace LeanCfgProject
namespace TCS1

universe u v

section OccupiedSubstringBuckets

variable {α : Type u} {M : Type v}
variable [DecidableEq α] [Monoid M] [Fintype M]

/-- A finite bucket key candidate is decoded from one old two-cut slot. -/
noncomputable def substringBucketKeys
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α)) :
    Finset ((Word α × Word α) × M) := by
  classical
  exact Finset.univ.image
    (fun s : ReconstructionFactorSlot K =>
      let X := reconstructionFactorSlotNonterminal s
      ((X.leftContext, X.rightContext), H.h X.factor))

/-- Every observed nonempty factor gives an explicitly enumerated key. -/
theorem substringBucketKeys_contains_observed
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α))
    {x p q : Word α}
    (hobs : Observed K x p q) :
    ((p, q), H.h x) ∈ substringBucketKeys H K := by
  classical
  unfold substringBucketKeys
  apply Finset.mem_image.mpr
  refine ⟨observedReconstructionFactorSlot K hobs,
    Finset.mem_univ _, ?_⟩
  simp only [reconstructionFactorSlotNonterminal_observed]

/-- Any semantic v116 unary substitution is emitted by two factors
    within one of the explicitly enumerated context/type buckets. -/
theorem substringBucketKeys_covers_unary
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α))
    {x y : Word α}
    (hrel : SubstringUnaryRelated H K x y) :
    ∃ p q : Word α, ∃ μ : M,
      ((p, q), μ) ∈ substringBucketKeys H K ∧
      ∃ A B : SubstringContextBucket H K p q μ,
        A.1.1 = x ∧ B.1.1 = y := by
  rcases hrel with ⟨htype, p, q, hpx, hpy⟩
  refine ⟨p, q, H.h x,
    substringBucketKeys_contains_observed H K hpx, ?_⟩
  refine ⟨⟨⟨x, ⟨p, q, hpx⟩⟩, ⟨hpx, rfl⟩⟩,
    ⟨⟨y, ⟨p, q, hpy⟩⟩, ⟨hpy, htype.symm⟩⟩,
    rfl, rfl⟩

/-- The number of ordered within-bucket unary candidates generated by
    this actual finite key enumeration is bounded cubically in ||K||. -/
theorem substringBucketKeys_unaryCandidateCount_le_cube
    (H : FixedFiniteMonoidHom α M)
    (K : Finset (Word α)) :
    (∑ b ∈ substringBucketKeys H K,
      (Fintype.card
        (SubstringContextBucket H K b.1.1 b.1.2 b.2)) ^ 2) ≤
      (reconstructionSampleNorm K) ^ 3 := by
  exact substringBucket_pairs_le_cube_unconditional H K
    (substringBucketKeys H K)

end OccupiedSubstringBuckets

end TCS1
end LeanCfgProject
