import LeanCfgProject.TCS1.GeneralCFGDerivationBridge
import LeanCfgProject.TCS1.FiniteCFGEncoding

/-!
# TCS #1 v134/v135: the introduction example `L = {a, aa}`

Manuscript v134 (kept in v135), Introduction, right after the definition of
fixed-`h` substitutability (unnumbered claim):

> For a minimal example, take `Σ = {a}` and `L = {a, aa}`.  Although
> `(λ,λ) ∈ D_L(a) ∩ D_L(aa)`, the context `(a,λ)` belongs to `D_L(a)` but not
> to `D_L(aa)`.  Thus `L` is not substitutable under the trivial typing.
> Under the parity morphism `h(aⁿ) = n mod 2` into `ℤ/2ℤ`, however, `a` and
> `aa` have distinct types and `L ∈ C_h`.

Here `Σ = {a}` is `Unit`, the trivial typing is the one-element monoid, and
the parity typing is `Multiplicative (ZMod 2)`.  Membership `L ∈ C_h` is
proved with an explicit two-production CFG generating exactly `L`.
-/

namespace LeanCfgProject
namespace TCS1
namespace V134IntroExample

/-- `L = {a, aa}` over the one-letter alphabet `Unit`. -/
def L : Set (Word Unit) := {w | w = [()] ∨ w = [(), ()]}

/-- The trivial typing into the one-element monoid. -/
def trivialHom : FixedFiniteMonoidHom Unit Unit where
  h := fun _ => ()
  map_nil := rfl
  map_append := fun _ _ => rfl

/-- The parity typing `h(aⁿ) = n mod 2`. -/
def parityHom : FixedFiniteMonoidHom Unit (Multiplicative (ZMod 2)) where
  h := fun w => Multiplicative.ofAdd ((w.length : ℕ) : ZMod 2)
  map_nil := by simp
  map_append := by
    intro u v
    simp [List.length_append, Nat.cast_add, ofAdd_add]

/-- The shared context `(λ, λ)` of `a` and `aa`. -/
theorem sharedContext_a_aa : HaveSharedContext L [()] [(), ()] :=
  ⟨[], [], by simp [L], by simp [L]⟩

/-- The context `(a, λ)` lies in `D_L(a)` but not in `D_L(aa)`. -/
theorem context_a_separates :
    ([()], ([] : Word Unit)) ∈ Distribution L [()] ∧
    ([()], ([] : Word Unit)) ∉ Distribution L [(), ()] := by
  constructor
  · simp [Distribution, L]
  · simp [Distribution, L]

/-- `L` is not substitutable under the trivial typing. -/
theorem not_trivial_substitutable : ¬ FixedHSubstitutable trivialHom L := by
  intro hs
  have hdist : Distribution L [()] = Distribution L [(), ()] :=
    hs (x := [()]) (y := [(), ()]) (by simp) (by simp) rfl sharedContext_a_aa
  have h1 := context_a_separates
  rw [hdist] at h1
  exact h1.2 h1.1

/-- Over a one-letter alphabet a word is determined by its length. -/
theorem unit_word_eq_of_length {x y : Word Unit} (h : x.length = y.length) :
    x = y :=
  List.ext_get h (fun _ _ _ => Subsingleton.elim _ _)

theorem length_le_two_of_mem_L {w : Word Unit} (hw : w ∈ L) :
    w.length ≤ 2 := by
  rcases hw with h | h <;> rw [h] <;> simp

/-- Under the parity typing `a` and `aa` have distinct types. -/
theorem parity_separates_a_aa : parityHom.h [()] ≠ parityHom.h [(), ()] := by
  intro h
  have h' := congrArg Multiplicative.toAdd h
  revert h'
  decide

/-- `L` is fixed-`h` substitutable for the parity typing. -/
theorem parity_substitutable : FixedHSubstitutable parityHom L := by
  intro x y hx hy hxy hshare
  obtain ⟨u, v, hux, huy⟩ := hshare
  have lx := length_le_two_of_mem_L hux
  have ly := length_le_two_of_mem_L huy
  simp only [List.length_append] at lx ly
  have hx1 : 1 ≤ x.length := List.length_pos_of_ne_nil hx
  have hy1 : 1 ≤ y.length := List.length_pos_of_ne_nil hy
  have hpar := congrArg Multiplicative.toAdd hxy
  simp only [parityHom, toAdd_ofAdd] at hpar
  rw [ZMod.natCast_eq_natCast_iff'] at hpar
  have hlen : x.length = y.length := by omega
  rw [unit_word_eq_of_length hlen]

/-- An explicit CFG `S → a | aa` for `L`. -/
def exampleGrammar : IndexedMixedCFG Unit Unit Bool where
  lhs := fun _ => ()
  rhs := fun
    | false => [Sum.inr ()]
    | true => [Sum.inr (), Sum.inr ()]

/-- The explicit grammar generates exactly `L`. -/
theorem exampleGrammar_language :
    MixedNonterminalLanguage exampleGrammar.toMixedRules () = L := by
  ext w
  change MixedDerives exampleGrammar.toMixedRules () w ↔ w ∈ L
  rw [mixedDerives_iff_ruleStep]
  constructor
  · rintro ⟨rhs, ⟨p, -, rfl⟩, hreal⟩
    cases p
    · change ∃ t, w = () :: t ∧ t = [] at hreal
      obtain ⟨t, rfl, rfl⟩ := hreal
      exact Or.inl rfl
    · change ∃ t, w = () :: t ∧ ∃ t₂, t = () :: t₂ ∧ t₂ = [] at hreal
      obtain ⟨t, rfl, t₂, rfl, rfl⟩ := hreal
      exact Or.inr rfl
  · rintro (rfl | rfl)
    · refine ⟨[Sum.inr ()], ⟨false, rfl, rfl⟩, ?_⟩
      exact ⟨[], rfl, rfl⟩
    · refine ⟨[Sum.inr (), Sum.inr ()], ⟨true, rfl, rfl⟩, ?_⟩
      exact ⟨[()], rfl, [], rfl, rfl⟩

/-- Summary of the introduction example: `L` is generated by a CFG, is not
substitutable under the trivial typing, and is `h`-substitutable for the
parity typing, which separates `a` from `aa`. -/
theorem intro_example_summary :
    MixedNonterminalLanguage exampleGrammar.toMixedRules () = L ∧
    ¬ FixedHSubstitutable trivialHom L ∧
    parityHom.h [()] ≠ parityHom.h [(), ()] ∧
    FixedHSubstitutable parityHom L :=
  ⟨exampleGrammar_language, not_trivial_substitutable,
    parity_separates_a_aa, parity_substitutable⟩

end V134IntroExample
end TCS1
end LeanCfgProject
