import LeanCfgProject.TCS1.V128PositiveWindowKernelForward
import LeanCfgProject.TCS1.GeneralCFGDerivationBridge
import LeanCfgProject.TCS1.FiniteCFGEncoding

/-!
# TCS #1 v135: class-union clause of `prop:li-window`

Manuscript `prop:li-window` (v135), last two sentences:

> `KL(Σ) = ⋃_{h : Σ* → M, h(Σ⁺) locally trivial} RS_h(Σ)`.
> The same equality holds after intersecting both sides with `CFL`.

The two pointwise halves were already verified
(`fixedWindowSubstitutable_of_positiveImageTrivial`,
`fixedWindowSubstitutable_has_locallyTrivialTyping`); this module states the
set-level equality itself, and its CFL-intersected form for finite indexed
CFGs.  The union ranges over all finite monoids in the universe of the
alphabet, which contains every concrete window monoid `h_{k,ℓ}`.
No nonempty-alphabet hypothesis is needed for this clause.
-/

namespace LeanCfgProject
namespace TCS1

universe u

section V135LiWindowClassUnion

variable {α : Type u} [Fintype α]

/-- `L ∈ KL(Σ)`: `(k,ℓ)`-substitutable for some window. -/
def InKL (L : Set (Word α)) : Prop :=
  ∃ k l : Nat, FixedWindowSubstitutable k l L

/-- `L ∈ ⋃_{h(Σ⁺) locally trivial} RS_h(Σ)`. -/
def InLocallyTrivialRSUnion (L : Set (Word α)) : Prop :=
  ∃ (M : Type u) (_ : Monoid M) (_ : Fintype M)
    (H : FixedFiniteMonoidHom α M),
    PositiveImageSandwichTrivial H ∧ FixedHSubstitutable H L

/-- **`prop:li-window`, class-union clause.** -/
theorem prop_liWindow_classUnion (L : Set (Word α)) :
    InKL L ↔ InLocallyTrivialRSUnion L := by
  constructor
  · rintro ⟨k, l, hsub⟩
    obtain ⟨hloc, hfix⟩ :=
      fixedWindowSubstitutable_has_locallyTrivialTyping (α := α) k l L hsub
    exact ⟨FixedWindowMonoid α k l, inferInstance, inferInstance,
      fixedWindowMonoidHom (α := α) k l, hloc, hfix⟩
  · rintro ⟨M, _, _, H, hloc, hsub⟩
    exact ⟨_, _, fixedWindowSubstitutable_of_positiveImageTrivial H hloc L hsub⟩

/-- Context-free languages, as generated by finite indexed CFGs. -/
def IndexedCFL (L : Set (Word α)) : Prop :=
  ∃ (N P : Type u) (_ : Fintype N) (_ : Fintype P)
    (G : IndexedMixedCFG N α P) (S : N),
    MixedNonterminalLanguage G.toMixedRules S = L

/-- **`prop:li-window`, class-union clause intersected with `CFL`.** -/
theorem prop_liWindow_classUnion_cfl (L : Set (Word α)) :
    (InKL L ∧ IndexedCFL L) ↔ (InLocallyTrivialRSUnion L ∧ IndexedCFL L) :=
  and_congr_left' (prop_liWindow_classUnion L)

end V135LiWindowClassUnion

end TCS1
end LeanCfgProject
