import LeanCfgProject.TCS1.V158DeltaStarDPDA
import LeanCfgProject.TCS1.DeltaStarProposition

/-!
# TCS #1 v158: `prop:nonlinear-rs-example` with its DCFL clause

`prop:nonlinear-rs-example` (v158): *"The language `Δ*` is deterministic
context-free, nonregular, and nonlinear, and it is `∼_{h⋆}`-substitutable.
Moreover it is not `(k,ℓ)`-substitutable for any fixed `k,ℓ ≥ 0`."*

The previous package `nonlinear_rs_example_full` proved every clause except
"deterministic context-free".  This file adds that clause through the explicit
DPDA `deltaStarDPDA` (`V158DeltaStarDPDA`) and states the language equality
for all three descriptions of `Δ*`: the DPDA, the displayed grammar
`S → T S | λ, T → a T b | λ`, and the Kleene star of the blocks `aⁿbⁿ`.
-/

namespace LeanCfgProject
namespace TCS1
namespace DeltaStar

universe u w

/-- The DPDA, the displayed CFG and the block star describe the same language. -/
theorem deltaStarDPDA_language_eq_star (x : Word Symbol) :
    x ∈ deltaStarDPDA.language ↔ StarDerives x := by
  rw [deltaStarDPDA_language, starDerives_iff_language]

theorem deltaStarDPDA_language_eq_displayed (x : Word Symbol) :
    x ∈ deltaStarDPDA.language ↔ SDerives x := by
  rw [deltaStarDPDA_language, displayedDerives_iff_language]

/--
**Full paper-facing `prop:nonlinear-rs-example`.**  Every clause of the
manuscript statement: deterministic context-free (explicit DPDA semantics),
generated by the displayed CFG and by a finite binary CFG, nonregular,
nonlinear, `h⋆`-substitutable, and outside every fixed window.
-/
theorem nonlinear_rs_example_full_dcfl :
    IsDCFL Language
      ∧ (∀ x : Word Symbol, x ∈ deltaStarDPDA.language ↔ StarDerives x)
      ∧ (∀ x : Word Symbol, SDerives x ↔ x ∈ Language)
      ∧ (initial.Finite ∧ InitialSetLanguage binaryGrammar initial = Language)
      ∧ (¬ FormalLanguage.IsRegular)
      ∧ (¬ RawLinearInitialRepresentable.{u, 0, w} Language)
      ∧ FixedHSubstitutable starTyping Language
      ∧ (∀ k l : Nat, ¬ FixedWindowSubstitutable k l Language) := by
  obtain ⟨h1, h2, h3, h4, h5, h6⟩ := nonlinear_rs_example_full.{u, w}
  exact ⟨deltaStar_isDCFL, deltaStarDPDA_language_eq_star, h1, h2, h3, h4, h5, h6⟩

end DeltaStar
end TCS1
end LeanCfgProject
